// Auto-generated by scripts/build-prompt-content.ts — DO NOT EDIT
// Run: npm run build:prompts

export const promptContent: Record<string, string> = {
  "ad-fatigue-report": `# Skill: Ad Fatigue Report

Detect creatives that are wasting budget due to audience exhaustion or declining engagement. Uses daily granularity over 7 days to identify fatigue patterns.

---

## Knowledge Base Grounding

- **wk-tw-001** (William Kast): "Frequency 2+ and CPA rising → creative fatigue, need fresh TOF creatives." Also: "CTR dropping and CPA rising → creative fatigue."
- **ds-pt-003** (Dara Saeed): "Frequency above 5 over 7 days signals audience saturation — creatives are hitting the same people."
- **lm-rc-003** (Lucas Moscon): Saturation curves — "beyond the inflection point, pushing more budget wastes money."
- **lm-rc-001** (Lucas Moscon): Cross-channel fatigue — TikTok CTR decline predicts Facebook decline 1-2 weeks later.
- **vs-nt-001** (Virendra Shekhawat): "Meta auto-shifts spend when creative degrades" — don't panic-pause, but do flag for rotation.
- **vs-nt-002** (Virendra Shekhawat): "Do not re-test degraded creatives. Exhaust all other angles first. Wait 3-6 months."

---

## Quick Method: Built-in Tool

Use \`get_meta_ad_fatigue\` — it runs a single API call and returns a full fatigue analysis with diagnosis and recommendations.

\`\`\`
get_meta_ad_fatigue(ad_account_id="act_123456789")
\`\`\`

Optional: scope to a campaign, change thresholds, or set a different conversion event.

---

## Manual Method: Step by Step

### Step 1: Pull Daily Ad-Level Data

\`\`\`
get_meta_insights(
  ad_account_id="act_123456789",
  level="ad",
  time_increment="1",
  fields="ad_id,ad_name,spend,impressions,clicks,ctr,cpm,frequency,actions,cost_per_action_type",
  date_preset="last_7d"
)
\`\`\`

### Step 2: Check Per Ad (daily granularity)

1. **Frequency** — flag if >3 (warning) or >5 (critical) over 7 days [ds-pt-003]
2. **CTR decline** — peak CTR vs last 3 days; flag if >30% decline [wk-tw-001 pattern #4]
3. **CPA trend** — is CPA rising while frequency rises? [wk-tw-001 pattern #1]
4. **Spend concentration** — is >50% of budget going to fatigued ads?

### Step 3: Diagnose

| Pattern | Diagnosis | Source |
|---------|-----------|--------|
| High frequency + rising CPA | Audience saturation | wk-tw-001 #1 |
| Declining CTR + rising CPA | Creative fatigue | wk-tw-001 #4 |
| High spend + high frequency + stable CPA | Approaching fatigue, monitor | ds-pt-003 |

### Step 4: Recommend

**FATIGUED ads:**
- Rotate with genuinely new creative concepts, not variations. Meta requires at least 25% visual difference for Andromeda to treat it as a new ad [lp-pt-001, oh-li-001].
- Change the hook (first 3 seconds) to access new audiences [oh-li-005].
- Do NOT re-test degraded creatives — wait 3-6 months [vs-nt-002].
- Meta will auto-shift spend away from degrading creatives [vs-nt-001].

**HEALTHY ads:**
- Let Meta manage allocation. Don't force spend to low-spend winners — Meta has determined scaling them would degrade performance [ds-pt-004].

---

## Output Template

\`\`\`markdown
## Ad Fatigue Report: [Account/Campaign Name]

### Summary
- X ads analyzed | Y fatigued | Z warning | W healthy
- Total spend: $X | Fatigued ad spend: $Y (Z%)

### Per-Ad Results
| Status | Ad | Spend | Freq | CTR Trend | CPA Trend | Diagnosis |
|--------|-----|-------|------|-----------|-----------|-----------|

### Recommendations
1. [Highest priority action]
2. [...]

### Knowledge Base References
- wk-tw-001, ds-pt-003, vs-nt-001, vs-nt-002, oh-li-001, lp-pt-001
\`\`\`
`,
  "attribution-analysis": `# Skill: Attribution & Conversion Validation

How to validate whether Meta-reported conversion numbers are real or inflated, using attribution window analysis and daily time-series data.

---

## Knowledge Base Grounding

- **lp-pt-003** (Lauren Petrullo): "Contribution vs attribution — ads feed conversions without getting last-click credit. Killing low-converting ads can collapse the funnel."
- **jm-pt-001** (related): Attribution modeling considerations for cross-channel measurement.

---

## When to Use This

- Comparing two campaigns with different CPI to rule out attribution as the cause
- Auditing a single campaign to understand conversion quality
- Investigating suspiciously high or low install numbers
- Validating whether view-through conversions are meaningful

---

## Step 1: Pull Multi-Window Attribution Data

\`\`\`
get_meta_insights(
  ad_account_id="act_123456789",
  level="campaign",
  fields="actions,cost_per_action_type,action_values",
  date_preset="last_7d"
)
\`\`\`

Note: For multi-window analysis, you may need direct API calls with \`action_attribution_windows=1d_click,7d_click,28d_click,1d_view\`.

Extract install counts for each window:

| Window | Installs | CPI |
|---|---|---|
| 1d_click (default) | | |
| 7d_click | | |
| 28d_click | | |
| 1d_view | | |

---

## Step 2: Check Delayed Conversion Uplift

Calculate:
- **1d → 7d uplift**: \`(7d_installs - 1d_installs) / 1d_installs × 100\`
- **7d → 28d uplift**: \`(28d_installs - 7d_installs) / 7d_installs × 100\`

### Interpretation

| 1d→7d Uplift | Signal |
|---|---|
| 10-20% | Healthy — users consider and return within a week |
| 3-5% | Low-intent — if they don't install immediately, they never will |
| >30% | Suspicious — investigate if attribution is overcounting |
| <1% | Either very direct-response creative, or very poor audience |

### Example from ROLA vs MX analysis
- ROLA: +14.0% (1d→7d) — healthy delayed consideration
- MX: +4.1% (1d→7d) — low-intent traffic confirmed

---

## Step 3: Analyze View-Through Ratio

Calculate: \`1d_view installs / 1d_click installs × 100\`

### Interpretation

| View-Through Ratio | Signal |
|---|---|
| 5-15% | Normal for app install campaigns |
| >25% | Possible attribution inflation — Meta counting impressions as conversions |
| <3% | Very click-driven campaign, view-through not a factor |

When comparing campaigns: if both have similar view-through ratios (~8-12%), attribution mechanics are comparable and the difference in CPI is real.

**Contribution vs attribution** [lp-pt-003]: Even if an ad has low direct conversions, it may be contributing to the funnel. View-through and assisted conversions indicate ads that are "feeding" the pipeline without getting last-click credit. Killing these ads can collapse the funnel.

---

## Step 4: Use Daily Time-Series for Consistency Check

\`\`\`
get_meta_insights(
  ad_account_id="act_123456789",
  level="campaign",
  fields="spend,impressions,actions",
  time_increment="1",
  date_preset="last_14d"
)
\`\`\`

Check:
- **Daily CPI consistency**: Stable CPI day-over-day = real performance. Wild swings = possible issues.
- **Install/impression ratio**: Should be relatively stable.
- **Weekend vs weekday patterns**: Normal to see dips; abnormal to see 5x swings.
- **Spend vs installs correlation**: If spend goes up but installs stay flat, Meta is buying junk inventory.

### Red flags in daily data
- Day with $800 spend and 34 installs next to day with $800 spend and 77 installs → inconsistent audience quality
- Steady spend but declining daily installs over 2 weeks → audience exhaustion
- Install spikes on specific days without corresponding spend increase → possible attribution lag

---

## Step 5: Cross-Reference with Creative Performance

\`\`\`
get_meta_insights(
  ad_account_id="act_123456789",
  level="ad",
  fields="ad_name,spend,impressions,actions",
  sort="spend_descending",
  limit=20
)
\`\`\`

For each top ad, check:
- Is the 1d_view count suspiciously close to 1d_click? (possible overcounting)
- Does the 7d_click show meaningful uplift over 1d_click? (delayed intent)
- Are there ads with very high spend but almost no 1d_click installs and lots of 1d_view? (view-through inflated)

---

## SKAN / iOS Attribution Notes

Meta does NOT expose raw SKAN data through the standard Insights API:
- \`skan_cv_app_install\`, \`skan_conversion\`, \`skan_campaign_id\`, \`skan_conversion_id\` → all return field validation errors
- \`signal_source_bucket\` breakdown → returns data but the field is always empty
- \`conversions\` field → no SKAN-specific action types appear

**What Meta does**: Receives SKAN postbacks from Apple and blends them into the modeled \`mobile_app_install\` numbers. The install counts you see are Meta's modeled estimates, not raw counts.

**To get raw SKAN postbacks**: You need an MMP (Adjust, AppsFlyer, Branch, Kochava) that receives SKAN postbacks independently from Apple.

---

## Output Template

\`\`\`markdown
## Attribution Analysis: [Campaign Name]

### Attribution Windows
| Window | Installs | CPI |
|---|---|---|
| 1d_click | X | $Y |
| 7d_click | X | $Y |
| 28d_click | X | $Y |
| 1d_view | X | $Y |

### Delayed Uplift: X% (1d→7d) — [healthy/low-intent/suspicious]
### View-Through Ratio: X% — [normal/inflated/minimal]
### Daily Consistency: [stable/unstable/declining]

### Contribution Warning [lp-pt-003]
[Note any ads that may be contributing to the funnel without getting direct credit]

### Conclusion
[Is the conversion data trustworthy? What does the attribution pattern reveal?]

### Knowledge Base References
- lp-pt-003
\`\`\`
`,
  "audience-composition": `# Skill: Audience Composition Report

Reveal who is actually converting and at what cost, by age and gender. Identifies mismatches between spend allocation and conversion efficiency.

---

## Knowledge Base Grounding

- **mb-li-010** (Marcus Burke): "Different creatives attract wildly different age demographics. Trial CVR by age: 18-24=18%, 25-34=26%, 35-44=32%, 45-54=44%, 55-64=48%, 65+=42%. Ads that attract older users are more valuable."
- **mb-li-006** (Marcus Burke): "App Promotion campaigns skew young (Reels-heavy). Web Sales campaigns skew older (Feed). Choose campaign type based on the demographic you want to reach."
- **mb-li-005** (Marcus Burke): "One price = one audience. Without offers for price-sensitive users, you'll never efficiently scale on Reels for younger demos."
- **mb-li-008** (Marcus Burke): "Value Rules let you set custom bid modifiers for age, gender, placement within the same broad-targeting ad set."
- **oh-li-003** (Olly Hudson): "Persona-based ads unlock new audiences 89% of the time."

---

## Procedure

### Step 1: Pull Age × Gender Breakdown

\`\`\`
get_meta_insights(
  ad_account_id="act_123456789",
  level="account",
  fields="spend,impressions,clicks,ctr,actions,cost_per_action_type",
  breakdowns="age,gender",
  date_preset="last_7d"
)
\`\`\`

### Step 2: Build Heatmap

Create an age × gender matrix showing:
- Spend per cell
- CPA per cell
- Conversions per cell
- % of total spend per cell

### Step 3: Analyze

1. **Which age groups get the most spend?**
2. **Which age groups have the best CPA?**
3. **Are high-value segments (35+) being reached?** [mb-li-010: they convert 2-3x better for subscription apps]
4. **Is budget concentrated on young demographics due to app campaign skew?** [mb-li-006]
5. **Spend vs efficiency mismatch**: flag if an age group gets >30% of spend but has CPA >1.5x average

### Step 4: Recommend

- If 35+ has better CPA but <20% of spend: "Consider adding Web Sales campaigns to reach older demographics on Feed [mb-li-006]. App Promotion campaigns are Reels-heavy and naturally skew young."
- If age CPA varies >2x: "Set up Value Rules with age-based bid modifiers to reflect actual conversion value [mb-li-008, mb-li-010]."
- If all spend goes to one age group: "Build persona-based creatives targeting different motivators to unlock new audiences [oh-li-003]."
- If younger demos have bad CPA: "Consider pricing variance — offer discounts for price-sensitive younger audiences [mb-li-005]."

---

## Output Template

\`\`\`markdown
## Audience Composition Report: [Account Name]

### Age × Gender Heatmap
| Age | Male Spend (CPA) | Female Spend (CPA) | Total Spend | Total CPA | % of Spend |
|-----|-------------------|---------------------|-------------|-----------|------------|
| 18-24 | $X ($Y) | $X ($Y) | $X | $Y | Z% |
| 25-34 | ... | ... | ... | ... | ... |
| 35-44 | ... | ... | ... | ... | ... |
| 45-54 | ... | ... | ... | ... | ... |
| 55-64 | ... | ... | ... | ... | ... |
| 65+   | ... | ... | ... | ... | ... |

### Key Findings
1. [Best performing segment]
2. [Worst performing segment]
3. [Biggest mismatch between spend and efficiency]

### Recommendations
1. [...]
2. [...]

### Knowledge Base References
- mb-li-010, mb-li-006, mb-li-005, mb-li-008, oh-li-003
\`\`\`
`,
  "audit-meta-account": `# Skill: Audit a Meta Ad Account

Run a structured audit of a Meta ad account against industry best practices from the knowledge base. Produces findings, baseline metrics, and prioritized recommendations.

---

## Knowledge Base Grounding

- **mb-li-002** (Marcus Burke): "Force deconsolidation — split creative types into separate ad sets to prevent self-cannibalization."
- **mb-li-003** (Marcus Burke): "Signal quality > signal volume. Train the algorithm on the event that matters most."
- **mb-li-006** (Marcus Burke): "App Promotion and Web Sales campaigns access different audiences. Scaled brands use both."
- **mb-li-008** / **mb-li-009** (Marcus Burke): Value Rules — bid differently on age, gender, placement within the same ad set.
- **mb-cd-001** (Marcus Burke): "EAC — web campaigns with in-app conversion feedback for subscription apps."
- **ds-pt-005** (Dara Saeed): "ASC campaigns need minimum 20 creatives for optimal performance."
- **lp-pt-001** (Lauren Petrullo): "Meta requires at least 25% creative difference for Andromeda."
- **lp-pt-002** (Lauren Petrullo): "Minimum 6 creatives per offering — 6 unique concepts or 2 concepts × 3 formats."
- **oh-li-001** (Olly Hudson): "Andromeda treats ads with similar first 3 seconds as identical."
- **oh-li-003** (Olly Hudson): "Persona-based ads unlock new audiences 89% of the time."
- **br-li-001** (Ben Radack): "CBO scaling with monthly winner rotation."
- **wk-tw-001** (William Kast): 4 diagnostic metric patterns for performance issues.

---

## Prerequisites

- Meta Marketing API access token (user provides via META_ACCESS_TOKEN)
- Access to MCP tools: \`get_meta_campaigns\`, \`get_meta_adsets\`, \`get_meta_ads\`, \`get_meta_insights\`, \`search_insights\`, \`get_insight\`
- Ad account ID (e.g., \`act_123456789\`)

## Procedure

### Step 1: Gather Account Structure

Use the Meta tools to pull structure:

\`\`\`
get_meta_campaigns(ad_account_id="act_123456789")
get_meta_adsets(ad_account_id="act_123456789")
get_meta_ads(ad_account_id="act_123456789")
\`\`\`

Record:
- Total active campaigns, ad sets, and ads
- Campaign objectives in use
- Bid strategies in use
- Budget distribution across campaigns
- Creative format distribution (video, image, carousel)

### Step 2: Gather Performance Metrics

Pull last 7 days of performance data (rate-limit safe):

\`\`\`
get_meta_insights(ad_account_id="act_123456789", level="campaign", date_preset="last_7d")
get_meta_insights(ad_account_id="act_123456789", level="account", breakdowns="age,gender", date_preset="last_7d")
get_meta_insights(ad_account_id="act_123456789", level="campaign", breakdowns="publisher_platform,platform_position", date_preset="last_7d")
\`\`\`

Record baseline metrics:
- Total spend, CPA, ROAS
- CPA by age group
- CPA by placement
- Top/bottom performing campaigns and ad sets

### Step 3: Analyze Against Best Practices

Use \`search_insights\` and \`get_insight\` to pull relevant knowledge. Evaluate:

#### Campaign Architecture
- [ ] Is the account over-consolidated (too few campaigns)? [mb-li-002]
- [ ] Are creative types mixed within ad sets (self-cannibalization risk)? [mb-li-002]
- [ ] Is there a mix of App Promotion and Web campaigns? [mb-li-006]
- [ ] Are campaign objectives aligned with business goals?
- [ ] Does the ASC campaign have 20+ creatives? [ds-pt-005]

#### Creative Strategy
- [ ] How many distinct creative concepts are active? Minimum 6 per offering [lp-pt-002]
- [ ] What's the ratio of video to static to carousel?
- [ ] Are creatives at least 25% visually different? [lp-pt-001]
- [ ] Do ads have different first 3 seconds (hooks)? [oh-li-001]
- [ ] Are there persona-based ads targeting different motivators? [oh-li-003]
- [ ] Is there a creative testing structure in place?

#### Audience & Targeting
- [ ] What's the age composition of spend and conversions? [mb-li-010]
- [ ] Are high-value age segments (35+) being reached?
- [ ] Is targeting broad or narrow? Is it appropriate?

#### Bid Strategy & Value Rules
- [ ] What bid strategies are in use?
- [ ] Are Value Rules configured? On which dimensions? [mb-li-008, mb-li-009]
- [ ] Are bid/cost caps set appropriately for the campaign type? [br-li-001]

#### Signal Quality
- [ ] What optimization events are campaigns using? [mb-li-003]
- [ ] Is the account optimizing for the deepest funnel event possible?
- [ ] Is CAPI configured for web campaigns?

#### Funnel Strategy
- [ ] Is the account app-only or does it include web funnels?
- [ ] For subscription apps: are there web-to-app campaigns reaching older demographics? [mb-li-006]
- [ ] Is EAC (External Attribution) being used? [mb-cd-001]

### Step 4: Score and Prioritize

Rate each category on a scale:
- **Green**: Well-optimized, minor tweaks only
- **Yellow**: Room for improvement, moderate impact
- **Red**: Significant issue, high-impact fix needed

### Step 5: Generate Output

Produce a structured output with:

\`\`\`json
{
  "ad_account_id": "act_123456789",
  "platform": "meta",
  "audit_date": "2026-03-10T00:00:00Z",
  "findings": {
    "campaign_architecture": {
      "score": "yellow",
      "issues": ["All creatives in single ad set — self-cannibalization risk [mb-li-002]"],
      "positives": ["Good campaign objective selection"]
    },
    "creative_strategy": { "score": "...", "issues": [], "positives": [] },
    "audience_targeting": { "score": "...", "issues": [], "positives": [] },
    "bid_strategy": { "score": "...", "issues": [], "positives": [] },
    "signal_quality": { "score": "...", "issues": [], "positives": [] },
    "funnel_strategy": { "score": "...", "issues": [], "positives": [] }
  },
  "baseline_metrics": {
    "total_spend_7d": 12000,
    "avg_cpa": 12.50,
    "cpa_by_age": { "18-24": 18.00, "25-34": 14.00, "35-44": 10.00, "45+": 8.50 },
    "top_placements": ["instagram_reels", "facebook_feed"],
    "active_campaigns": 5,
    "active_ad_sets": 12,
    "active_ads": 45
  },
  "recommendations": [
    {
      "priority": 1,
      "category": "campaign_architecture",
      "action": "Split creative types into separate ad sets to prevent self-cannibalization [mb-li-002]",
      "expected_impact": "high",
      "effort": "low",
      "related_insights": ["mb-li-002", "lp-pt-001"]
    }
  ]
}
\`\`\`

---

## Notes

- Always explain WHY each finding matters, referencing specific insight IDs from the knowledge base
- Prioritize recommendations by impact/effort ratio
- Compare the account's patterns against the knowledge base, not just generic best practices
- Use \`get_insight\` to read full insight text when citing specific recommendations
- This audit is a starting point — encourage the user to run it periodically to track improvement
`,
  "architecture-review": `# Skill: Campaign Architecture Review

Evaluate whether the account structure supports or limits scale. Structure-only analysis — no insights API needed, just campaigns/adsets/ads.

---

## Knowledge Base Grounding

- **mb-li-002** (Marcus Burke): "Force deconsolidation — split creative types and messaging angles into separate ad sets to prevent self-cannibalization."
- **mb-li-003** (Marcus Burke): "Signal quality > signal volume. Always train the algorithm on the event that matters most."
- **mb-li-006** (Marcus Burke): "App Promotion and Web Sales campaigns access different audiences. Scaled brands use both."
- **mb-li-011** (Marcus Burke): "Breakthrough requires: creative diversity, architecture for scale, funnel expansion, organic amplification."
- **mb-cd-001** (Marcus Burke): "EAC — web campaigns with in-app conversion feedback for subscription apps."
- **ds-pt-005** (Dara Saeed): "ASC campaigns need minimum 20 creatives for optimal performance."
- **br-li-001** (Ben Radack): "CBO scaling with monthly winner rotation — new ad set each month for that month's proven winners."
- **br-li-002** (Ben Radack): "Zombie campaign — low cost cap CBO where every failed creative gets a second chance."
- **lp-pt-001** (Lauren Petrullo): "Meta requires at least 25% creative difference for Andromeda."
- **lp-pt-002** (Lauren Petrullo): "Minimum 6 creatives per offering — 6 unique concepts or 2 concepts × 3 formats."

---

## Procedure

### Step 1: Pull Account Structure

3 API calls — structure only, no insights:

\`\`\`
get_meta_campaigns(ad_account_id="act_123456789")
get_meta_adsets(ad_account_id="act_123456789")
get_meta_ads(ad_account_id="act_123456789")
\`\`\`

### Step 2: Run Architecture Checks

| Check | What | Flag | Source |
|-------|------|------|--------|
| Over-consolidation | All ads in 1-2 campaigns | ⚠ Self-cannibalization risk | mb-li-002 |
| Creative type mixing | Video + static + carousel in same ad set | ⚠ Prevents unique reach per format | mb-li-002 |
| Creative count | <6 ads per ad set / <20 in ASC | ⚠ Insufficient for Andromeda | lp-pt-002, ds-pt-005 |
| Campaign type diversity | App-only, no web campaigns | ⚠ Missing older demographics | mb-li-006, mb-li-011 |
| Optimization event | Upper-funnel event (installs) when deeper events exist | ⚠ Signal quality issue | mb-li-003 |
| Bid strategy | No cost caps on scaling campaigns | ⚠ No spend protection | br-li-001 |
| EAC | No web2app campaigns for subscription app | 💡 Opportunity | mb-cd-001 |
| Zombie campaign | No low-cap recovery campaign | 💡 Opportunity | br-li-002 |
| Creative similarity | Ads with likely similar first 3 seconds | ⚠ Andromeda treats them as identical | oh-li-001, lp-pt-001 |

### Step 3: Score and Prioritize

Rate each check:
- ✅ **Good**: Well-structured
- ⚠ **Issue**: Problem that limits scale
- 💡 **Opportunity**: Missing capability that could unlock growth

---

## Output Template

\`\`\`markdown
## Campaign Architecture Review: [Account Name]

### Structure Summary
- Active campaigns: X | Ad sets: Y | Ads: Z
- Campaign types: [list]
- Bid strategies: [list]

### Architecture Checks
| Check | Status | Finding | Action | Source |
|-------|--------|---------|--------|--------|
| Over-consolidation | ⚠ | All 30 ads in 1 campaign | Split by creative type into separate ad sets | mb-li-002 |
| Creative count | ⚠ | Avg 3 ads per ad set | Add more concepts — minimum 6 per offering | lp-pt-002 |
| Campaign type diversity | ⚠ | App-only | Add Web Sales campaigns for older demos | mb-li-006 |
| ... | ... | ... | ... | ... |

### Opportunities
1. **EAC campaigns** [mb-cd-001]: Web campaigns with in-app conversion feedback for subscription apps — reaches demographics that App Promotion misses.
2. **Zombie campaign** [br-li-002]: Low cost cap CBO where failed creatives get a second chance — recovers value from retired ads.

### Recommended Architecture
[Proposed campaign structure based on findings]

### Knowledge Base References
- mb-li-002, mb-li-003, mb-li-006, mb-li-011, mb-cd-001, ds-pt-005, br-li-001, br-li-002, lp-pt-001, lp-pt-002
\`\`\`
`,
  "campaign-comparison": `# Skill: Campaign Comparison Methodology

Reusable step-by-step framework for comparing any two Meta campaigns to identify why one outperforms the other.

---

## Knowledge Base Grounding

- **wk-tw-001** (William Kast): 4 diagnostic metric patterns — Frequency↑+CPA↑ (fatigue), CPM↑+CPA↑ (saturation), CPA↑+CVR↓ (LP mismatch), CTR↓+CPA↑ (creative fatigue).
- **lp-pt-003** (Lauren Petrullo): "Contribution vs attribution — ads feed conversions without getting last-click credit."
- **jl-pt-004** (Jon Loomer): "Don't turn off underperforming ads if aggregate performance is good — they may play a halo role."
- **oh-li-001** (Olly Hudson): "Andromeda treats ads with similar first 3 seconds as identical."

---

## Step 1: Pull Campaign Settings Side-by-Side

\`\`\`
get_meta_campaigns(ad_account_id="act_123456789")
\`\`\`

Then filter for the two campaigns being compared.

Compare: objective, bid strategy, daily budget, buying type, how long each has been running.

**Watch for**: Budget set at campaign level vs ad set level. One campaign may have 2x the budget — that alone can explain saturation effects.

---

## Step 2: Pull Ad Set Targeting & Placement Differences

\`\`\`
get_meta_adsets(ad_account_id="act_123456789", campaign_id="CAMPAIGN_A_ID")
get_meta_adsets(ad_account_id="act_123456789", campaign_id="CAMPAIGN_B_ID")
\`\`\`

Compare:
- **Geo-targeting**: Single country vs multi-country
- **Placements**: Which publisher_platforms and positions are enabled
- **Audience**: Age range, exclusions, Advantage+ settings
- **Bid amount**: Same cost cap? Different?

**Watch for**: Extra placements in the underperformer (instream_video, reels_overlay, threads are common waste placements for iOS app installs).

---

## Step 3: Pull Aggregate Insights

\`\`\`
get_meta_insights(
  ad_account_id="act_123456789",
  level="campaign",
  fields="campaign_id,campaign_name,spend,impressions,clicks,cpm,cpc,ctr,reach,frequency,actions,cost_per_action_type",
  date_preset="last_7d"
)
\`\`\`

Build comparison table:

| Metric | Campaign A | Campaign B | Ratio |
|---|---|---|---|
| Spend | | | |
| Impressions | | | |
| CTR | | | |
| CPM | | | |
| Frequency | | | |
| Installs | | | |
| **CPI** | | | |

**Apply Kast's diagnostic framework** [wk-tw-001] to interpret the metric differences:
- If Campaign B has higher CPM AND higher CPA → audience saturation or poor engagement
- If Campaign B has declining CTR AND higher CPA → creative fatigue
- If Campaign B has higher CPA AND lower CVR → ad-to-landing-page mismatch

---

## Step 4: Run Funnel Analysis

Calculate conversion rates at each step:

| Step | Campaign A | Campaign B |
|---|---|---|
| Impressions | | |
| → Click Rate | | |
| → Install Rate from Impressions | | |

**Watch for**: If Campaign B sends MORE people to the app store but converts at a lower rate, Meta is sending low-intent traffic.

---

## Step 5: Break Down by Placement

\`\`\`
get_meta_insights(
  ad_account_id="act_123456789",
  level="campaign",
  fields="spend,impressions,cpm,ctr,actions,cost_per_action_type",
  breakdowns="publisher_platform,platform_position",
  date_preset="last_7d"
)
\`\`\`

For each placement, calculate CPI. Compare:
- Which placements exist in one campaign but not the other?
- What's the CPI range? Tight ($3-$6) = healthy. Wide ($8-$84) = waste.
- How much spend goes to the worst placements?

See \`skills/placement-audit.md\` for the full placement audit methodology.

---

## Step 6: Break Down by Country (Multi-Geo Campaigns)

\`\`\`
get_meta_insights(
  ad_account_id="act_123456789",
  level="campaign",
  breakdowns="country",
  date_preset="last_7d"
)
\`\`\`

**Watch for**: One country eating the majority of budget with poor results.

---

## Step 7: Compare Same Creatives Across Campaigns

\`\`\`
get_meta_insights(
  ad_account_id="act_123456789",
  level="ad",
  fields="ad_name,adset_name,spend,impressions,actions,cost_per_action_type",
  sort="spend_descending",
  limit=50
)
\`\`\`

Match ads by creative name across campaigns.

If the same creatives consistently perform 2-3x worse in one campaign, the problem is **not** creative quality — it's the campaign environment.

**Check for creative similarity** [oh-li-001]: Are ads in the underperforming campaign all variations of the same concept (similar first 3 seconds)? Andromeda treats them as identical, reducing effective creative diversity.

**Attribution contribution warning** [lp-pt-003, jl-pt-004]: Before pausing underperforming ads, check if aggregate ad set performance is good. Low-converting ads may be contributing to the funnel without getting last-click credit.

---

## Step 8: Identify Root Causes

Use this decision tree:

1. **Same creatives worse in one campaign?** → Problem is campaign-level, not creative
2. **Funnel leaks at app store step?** → Low-intent traffic
3. **Bad placements burning budget?** → Placement waste
4. **One campaign spends 2x+ in single market?** → Budget saturation
5. **CPM cheap but CPI high?** → Cheap impressions ≠ cheap installs

Apply Kast's diagnostic framework [wk-tw-001] to determine which pattern matches, then follow the recommended action for that pattern.

---

## Output Template

\`\`\`markdown
## Campaign Comparison: [A] vs [B]

### Setup Differences
- [Key difference 1]
- [Key difference 2]

### Performance Gap
- CPI: $X vs $Y (Z× difference)

### Diagnosis [per wk-tw-001 framework]
- [Pattern identified and what it means]

### Root Causes
1. [Primary cause]
2. [Secondary cause]

### Recommended Actions
1. [Action 1]
2. [Action 2]

### Knowledge Base References
- wk-tw-001, lp-pt-003, jl-pt-004, oh-li-001
\`\`\`
`,
  "creative-performance": `# Skill: Creative Performance Report

Categorize every active ad by health status and provide specific next steps per category, grounded in knowledge base insights.

---

## Knowledge Base Grounding

- **ds-pt-001** (Dara Saeed): "Only optimize based on primary metrics (CPA, ROAS). A low CTR or high CPM doesn't mean an ad is failing if the CPA is profitable."
- **ds-pt-004** (Dara Saeed): "Meta has determined that scaling 'more profitable' low-spend ads further would degrade performance. Don't try to force spend to them."
- **jl-pt-004** (Jon Loomer): "In BAU campaigns, don't turn off underperforming ads if aggregate performance is good. They may play a halo role."
- **lp-pt-003** (Lauren Petrullo): "Contribution vs attribution — ads feed conversions without getting last-click credit. Killing low-converting ads can collapse the funnel."
- **vs-nt-001** (Virendra Shekhawat): "Meta auto-shifts spend when creative degrades."
- **mb-li-001** (Marcus Burke): "Creative unlocks scale, iterations maintain it. Only genuinely new concepts unlock new audiences."
- **oh-li-001** (Olly Hudson): "Andromeda treats ads with similar first 3 seconds as identical."
- **lp-pt-001** (Lauren Petrullo): "Meta requires at least 25% creative difference."
- **lp-pt-002** (Lauren Petrullo): "Minimum 6 creatives per offering — 6 unique concepts or 2 concepts × 3 formats."

---

## Procedure

### Step 1: Pull Ad-Level Insights

\`\`\`
get_meta_insights(
  ad_account_id="act_123456789",
  level="ad",
  fields="ad_id,ad_name,adset_id,adset_name,spend,impressions,clicks,ctr,cpm,frequency,actions,cost_per_action_type",
  date_preset="last_7d",
  sort="spend_descending",
  limit=50
)
\`\`\`

### Step 2: Determine Target CPA

Ask the user for their target CPA, or calculate account average CPA from the data.

### Step 3: Categorize Each Ad

| Category | Criteria | Action (grounded in KB) |
|----------|----------|------------------------|
| **Scaling** | High spend (>10% of total), CPA ≤ target | Let it run. Don't micro-optimize. Extract creative learnings for new concepts [mb-li-001]. |
| **Promising** | Low spend, CPA ≤ target | Don't force more spend — Meta has determined scaling would degrade it [ds-pt-004]. Analyze what makes it work and apply learnings to new ads. |
| **Contributing** | Getting impressions, low/no conversions, but aggregate ad set is healthy | Likely playing a halo role [jl-pt-004, lp-pt-003]. Do NOT pause. Meta shows it for a reason. |
| **Fatiguing** | Frequency >3, CTR declining or CPA rising | Prepare replacement with genuinely different visuals [oh-li-001, lp-pt-001]. Meta will auto-shift spend [vs-nt-001]. |
| **Dead weight** | High spend (>5% of total), CPA >2x target, for >7 days | Consider pausing only if aggregate ad set performance is also bad [jl-pt-004]. |

### Step 4: Creative Diversity Assessment

- How many genuinely different concepts are running? (not just variations)
- Are there format differences (video/static/carousel) or just copy changes? [lp-pt-001: need 25% visual difference]
- Minimum 6 creatives per offering [lp-pt-002]

---

## Output Template

\`\`\`markdown
## Creative Performance Report: [Account Name]

### Summary
- X ads analyzed across Y ad sets
- Total spend: $X | Average CPA: $Y
- Z scaling | W promising | V contributing | U fatiguing | T dead weight

### Ad Categories
#### 🟢 Scaling (X ads, $Y spend)
| Ad | Spend | CPA | CTR | Notes |
|----|-------|-----|-----|-------|

#### 💡 Promising (X ads, $Y spend)
| Ad | Spend | CPA | CTR | Notes |
|----|-------|-----|-----|-------|

#### 🔵 Contributing (X ads, $Y spend)
| Ad | Spend | Impressions | Conversions | Ad Set Health |
|----|-------|-------------|-------------|---------------|

#### 🟡 Fatiguing (X ads, $Y spend)
| Ad | Spend | Freq | CTR Trend | CPA | Diagnosis |
|----|-------|------|-----------|-----|-----------|

#### 🔴 Dead Weight (X ads, $Y spend)
| Ad | Spend | CPA | vs Target | Ad Set CPA |
|----|-------|-----|-----------|------------|

### Creative Diversity
- Unique concepts: X
- Format mix: Y% video, Z% static, W% carousel
- [Assessment and gaps]

### Recommendations
1. [...]

### Knowledge Base References
- ds-pt-001, ds-pt-004, jl-pt-004, lp-pt-003, vs-nt-001, mb-li-001, oh-li-001, lp-pt-001, lp-pt-002
\`\`\`
`,
  "placement-audit": `# Skill: Placement Efficiency Audit

How to identify and quantify placement waste in Meta app install campaigns.

---

## Knowledge Base Grounding

- **mb-li-006** (Marcus Burke): "App Promotion campaigns are Reels-heavy and skew young. Web campaigns have better placement distribution and scale on Feed."
- **mb-li-009** (Marcus Burke): "Placement-level Value Rules — bid differently on each placement within the same broad targeting ad set. Don't create separate placement-targeted campaigns."

---

## When to Use This

- Campaign has high CPI and you suspect placement waste
- Comparing an efficient vs inefficient campaign
- After enabling Advantage+ placements and wanting to check what Meta chose
- Before deciding whether to restrict placements or keep them broad

---

## Step 1: Pull Placement Breakdown

\`\`\`
get_meta_insights(
  ad_account_id="act_123456789",
  level="campaign",
  fields="spend,impressions,cpm,ctr,actions,cost_per_action_type",
  breakdowns="publisher_platform,platform_position",
  date_preset="last_7d"
)
\`\`\`

Returns one row per \`publisher_platform\` × \`platform_position\` combination.

---

## Step 2: Calculate CPI Per Placement

For each placement row:
\`\`\`
installs = actions where action_type == "mobile_app_install"
cpi = spend / installs (if installs > 0, else ∞)
\`\`\`

Build a table sorted by spend descending:

| Placement | Spend | Impressions | Installs | CPI | % of Total Spend |
|---|---|---|---|---|---|

---

## Step 3: Flag Waste Placements

**Rule of thumb**: Flag any placement where CPI > 3x the campaign average CPI.

### Common Waste Placements for iOS App Install Campaigns

| Placement | Typical Behavior | Why It's Wasteful |
|---|---|---|
| \`facebook/instream_video\` | Very high impressions, very low installs | Users watching videos don't want to leave; accidental clicks |
| \`facebook/facebook_reels_overlay\` | High impressions, very low installs | Overlay ads get impressions but no meaningful engagement |
| \`threads/threads_feed\` | Low volume, near-zero installs | Threads audience isn't app-install-receptive (yet) |
| \`audience_network/classic\` | Can drive volume but often low quality | Third-party apps, less intent |

**Campaign type context** [mb-li-006]: App Promotion campaigns are inherently Reels-heavy. If you need better placement distribution, consider Web Sales campaigns which scale more on Feed.

### Example from ROLA vs MX Analysis

**Efficient campaign (ROLA)** — only 6 placements, CPI range $3.06 - $6.86:
- instagram/reels: $3.37
- facebook/reels: $3.64
- instagram/stories: $3.64
- facebook/stories: $3.94
- instagram/feed: $3.06
- facebook/feed: $6.86

**Inefficient campaign (MX)** — 8 placements, CPI range $8.64 - $83.66:
- facebook/instream_video: **$83.66** (29 installs for $2,426)
- facebook/reels_overlay: **$56.98** (31 installs for $1,766)
- threads/threads_feed: **∞** (0 installs for $53)
- instagram/stories: $31.07
- facebook/feed: $20.93
- facebook/stories: $14.02
- instagram/reels: $10.12
- facebook/reels: $8.64

The 3 waste placements in MX burned **$4,245 for 60 installs ($70.75 CPI)** — but even without them, MX's core placements are 2-4x more expensive than ROLA's.

---

## Step 4: Quantify the Waste

Calculate:
- **Total waste spend**: Sum of spend on placements with CPI > 3x average
- **Waste installs**: Sum of installs from those placements
- **Waste CPI**: waste spend / waste installs
- **What-if CPI**: (total spend - waste spend) / (total installs - waste installs)

### Example
\`\`\`
MX total: $36,934 spend, 2,434 installs, $15.17 CPI

Waste placements: $4,245 spend, 60 installs
Without waste: $32,689 spend, 2,374 installs = $13.77 CPI

Savings: $1.40 CPI improvement (9.2% better)
But still 3.5x worse than ROLA — waste is a symptom, not the full cause
\`\`\`

---

## Step 5: Compare Placement Mix Between Campaigns

| Placement | Campaign A (% spend) | Campaign B (% spend) |
|---|---|---|
| instagram/reels | | |
| facebook/reels | | |
| facebook/feed | | |
| instagram/stories | | |
| facebook/stories | | |
| instagram/feed | | |
| [waste placements] | | |

**Watch for**:
- Campaign A has 80% spend on reels/stories (video-first, high-intent placements)
- Campaign B has 40% on feed + 12% on junk placements (broader, lower-intent)

---

## Step 6: Decision — Restrict vs Advantage+ vs Value Rules

### Option 1: Restrict Placements
**When**: Clear waste placements with CPI > 5x average, waste >10% of total budget, >30 days of data.

**Warning**: Restricting placements resets the learning phase. Monitor closely for 3-5 days.

### Option 2: Keep Advantage+ Broad
**When**: All placements within 2x of average CPI, campaign is new (<14 days), Advantage+ is still learning.

### Option 3: Placement Value Rules [mb-li-009]
**When**: You want to keep broad targeting but bid differently per placement. "This avoids fragmentation from creating separate placement-targeted campaigns."

Set up Placement-level Value Rules to bid lower on wasteful placements and higher on efficient ones, within the same ad set. This is the preferred approach when:
- You want to maintain broad delivery
- Waste is moderate (not extreme)
- You have enough data to know which placements work

---

## Step 7: Monitor After Changes

\`\`\`
get_meta_insights(
  ad_account_id="act_123456789",
  level="campaign",
  fields="spend,impressions,actions",
  time_increment="1",
  date_preset="last_14d"
)
\`\`\`

Check:
- Did CPI improve within 3-5 days?
- Did impression volume drop significantly?
- Did install volume stay stable or improve?
- Did CPM increase? (expected — higher-quality placements cost more)

---

## Output Template

\`\`\`markdown
## Placement Audit: [Campaign Name]

### Placement Performance
| Placement | Spend | Installs | CPI | Flag |
|---|---|---|---|---|
| | | | | OK / WASTE |

### Waste Summary
- Total waste: $X on Y placements
- Waste CPI: $Z (vs campaign average $W)
- Impact if removed: CPI improves from $A to $B

### Recommendation
[Restrict placements / Keep broad / Use Placement Value Rules [mb-li-009]]

### Knowledge Base References
- mb-li-006, mb-li-009
\`\`\`
`,
  "weekly-performance": `# Skill: Weekly Performance Snapshot

The "Monday morning check" — week-over-week health comparison with automatic diagnosis using Kast's diagnostic framework.

---

## Knowledge Base Grounding

- **wk-tw-001** (William Kast): The 4 core metric patterns that diagnose every Meta performance issue:
  1. Frequency↑ + CPA↑ → creative fatigue → need fresh TOF creatives
  2. CPM↑ + CPA↑ → audience saturation or poor engagement → new messaging, new audiences
  3. CPA↑ + CVR↓ → ad-to-landing-page mismatch → fix landing page alignment
  4. CTR↓ + CPA↑ → creative fatigue → need fresh TOF creatives
- **wk-tw-002** (William Kast): ROAS troubleshooting decision tree — CPM → CTR → AOV → CR, sequential isolation
- **ds-pt-001** (Dara Saeed): "Primary metrics (spend, CPA, ROAS) decide what works. Secondary metrics (frequency, CPM, CTR) explain why. Never make optimization decisions based on secondary metrics alone."
- **ds-pt-008** (Dara Saeed): "Analyze first, optimize second. Separate the two activities to avoid reactive decisions."

---

## Procedure

### Step 1: Pull This Week and Last Week Data

\`\`\`
# This week
get_meta_insights(
  ad_account_id="act_123456789",
  level="campaign",
  fields="campaign_id,campaign_name,spend,impressions,clicks,ctr,cpm,cpc,reach,frequency,actions,cost_per_action_type",
  date_preset="this_week_mon_today"
)

# Last week
get_meta_insights(
  ad_account_id="act_123456789",
  level="campaign",
  fields="campaign_id,campaign_name,spend,impressions,clicks,ctr,cpm,cpc,reach,frequency,actions,cost_per_action_type",
  date_preset="last_week_mon_sun"
)
\`\`\`

### Step 2: Compute Deltas

For each campaign, calculate week-over-week changes:
- Spend Δ%
- CPA Δ%
- CPM Δ%
- CTR Δ%
- Frequency Δ%
- Conversions Δ%

### Step 3: Apply Kast Diagnostic Framework [wk-tw-001]

For each campaign with CPA increase, check which pattern matches:

| Pattern | Diagnosis | Action |
|---------|-----------|--------|
| Frequency↑ + CPA↑ | Creative fatigue | Fresh TOF creatives needed |
| CPM↑ + CPA↑ | Audience saturation / poor engagement | New messaging, broader targeting |
| CPA↑ + CVR↓ | Ad-to-LP mismatch | Fix landing page alignment |
| CTR↓ + CPA↑ | Creative fatigue | New hooks, new creative concepts |

Remember: "Primary metrics decide what works. Secondary metrics explain why" [ds-pt-001].

### Step 4: Generate Action Items

Prioritize the top 3 highest-impact actions across all campaigns.

---

## Output Template

\`\`\`markdown
## Weekly Performance Snapshot — [Date Range]

### Account Summary
Total spend: $X (+Y% WoW) | Conversions: N (+Z% WoW) | Avg CPA: $X (+W% WoW)

### Campaign Health
| Campaign | Spend | CPA (Δ%) | CPM (Δ%) | CTR (Δ%) | Freq | Diagnosis |
|----------|-------|----------|----------|----------|------|-----------|
| Camp A   | $5K   | $12 (+8%)| $15 (+12%)| 1.2% (-5%)| 2.1 | ⚠ CPM+CPA↑: audience saturation [wk-tw-001 #2] |
| Camp B   | $3K   | $9 (-3%) | $11 (0%) | 1.8% (+2%)| 1.5 | ✅ Healthy |

### Diagnosis
[Per Kast framework, with insight IDs]

### Action Items
1. [Highest impact action]
2. [...]
3. [...]

> "Analyze first, optimize second" (ds-pt-008) — review this report fully before making changes.

### Knowledge Base References
- wk-tw-001, wk-tw-002, ds-pt-001, ds-pt-008
\`\`\`
`,
};
