// Auto-generated by scripts/build-prompt-content.ts — DO NOT EDIT
// Run: npm run build:prompts

export const promptContent: Record<string, string> = {
  "ad-fatigue-report": `# Skill: Ad Fatigue Report

Detect creatives that are wasting budget due to audience exhaustion or declining engagement. Uses daily granularity over 7 days to identify fatigue patterns.

---

## When to Use This

- Frequency is climbing and CPA is rising
- CTR has been declining over the past week
- User asks "are my ads getting tired?" or "should I refresh creatives?"
- Before a creative refresh sprint — to know which ads to replace first
- User mentions audience saturation or ad burnout

## What It Needs

**Option A — Meta API connected**: Provide \`ad_account_id\`. The \`get_meta_ad_fatigue\` tool handles this in a single call.

**Option B — CSV export** (no API needed):
- Go to **Meta Ads Manager** → **Ads** tab
- Date range: **Last 14 days**, broken down **by day** (use the "Breakdown" → "Time" → "Day" option before exporting)
- Columns: \`Ad name\`, \`Ad set name\`, \`Date\`, \`Spend\`, \`Impressions\`, \`Reach\`, \`Frequency\`, \`CTR (link)\`, \`CPM\`, \`Result\`, \`Cost per result\`
- Export as CSV and paste below.

## What It Produces

- Per-ad fatigue status: Healthy / Warning / Fatigued / Saturated
- Daily trend chart per flagged ad (frequency and CTR movement)
- Prioritized list of ads to rotate out, with timing recommendation

---

## Knowledge Base Grounding

- **wk-tw-001** (William Kast): "Frequency 2+ and CPA rising → creative fatigue, need fresh TOF creatives." Also: "CTR dropping and CPA rising → creative fatigue."
- **ds-pt-003** (Dara Saeed): "Frequency above 5 over 7 days signals audience saturation — creatives are hitting the same people."
- **lm-rc-003** (Lucas Moscon): Saturation curves — "beyond the inflection point, pushing more budget wastes money."
- **lm-rc-001** (Lucas Moscon): Cross-channel fatigue — TikTok CTR decline predicts Facebook decline 1-2 weeks later.
- **vs-nt-001** (Virendra Shekhawat): "Meta auto-shifts spend when creative degrades" — don't panic-pause, but do flag for rotation.
- **vs-nt-002** (Virendra Shekhawat): "Do not re-test degraded creatives. Exhaust all other angles first. Wait 3-6 months."

---

## Quick Method: Built-in Tool

Use \`get_meta_ad_fatigue\` — it runs a single API call and returns a full fatigue analysis with diagnosis and recommendations.

\`\`\`
get_meta_ad_fatigue(ad_account_id="act_123456789")
\`\`\`

Optional: scope to a campaign, change thresholds, or set a different conversion event.

---

## Manual Method: Step by Step

### Step 1: Pull Daily Ad-Level Data

\`\`\`
get_meta_insights(
  ad_account_id="act_123456789",
  level="ad",
  time_increment="1",
  fields="ad_id,ad_name,spend,impressions,clicks,ctr,cpm,frequency,actions,cost_per_action_type",
  date_preset="last_7d"
)
\`\`\`

### Step 2: Check Per Ad (daily granularity)

1. **Frequency** — flag if >3 (warning) or >5 (critical) over 7 days [ds-pt-003]
2. **CTR decline** — peak CTR vs last 3 days; flag if >30% decline [wk-tw-001 pattern #4]
3. **CPA trend** — is CPA rising while frequency rises? [wk-tw-001 pattern #1]
4. **Spend concentration** — is >50% of budget going to fatigued ads?

### Step 3: Diagnose

| Pattern | Diagnosis | Source |
|---------|-----------|--------|
| High frequency + rising CPA | Audience saturation | wk-tw-001 #1 |
| Declining CTR + rising CPA | Creative fatigue | wk-tw-001 #4 |
| High spend + high frequency + stable CPA | Approaching fatigue, monitor | ds-pt-003 |

### Step 4: Recommend

**FATIGUED ads:**
- Rotate with genuinely new creative concepts, not variations. Meta requires at least 25% visual difference for Andromeda to treat it as a new ad [lp-pt-001, oh-li-001].
- Change the hook (first 3 seconds) to access new audiences [oh-li-005].
- Do NOT re-test degraded creatives — wait 3-6 months [vs-nt-002].
- Meta will auto-shift spend away from degrading creatives [vs-nt-001].

**HEALTHY ads:**
- Let Meta manage allocation. Don't force spend to low-spend winners — Meta has determined scaling them would degrade performance [ds-pt-004].

---

## Output Template

\`\`\`markdown
## Ad Fatigue Report: [Account/Campaign Name]

### Summary
- X ads analyzed | Y fatigued | Z warning | W healthy
- Total spend: $X | Fatigued ad spend: $Y (Z%)

### Per-Ad Results
| Status | Ad | Spend | Freq | CTR Trend | CPA Trend | Diagnosis |
|--------|-----|-------|------|-----------|-----------|-----------|

### Recommendations
1. [Highest priority action]
2. [...]

### Knowledge Base References
- wk-tw-001, ds-pt-003, vs-nt-001, vs-nt-002, oh-li-001, lp-pt-001
\`\`\`
`,
  "admin-briefing": `# Admin Briefing

You are generating a morning briefing for the Mobile Growth MCP admin. Check all pending items and present a concise summary.

---

## When to Use This

- Admin starts their day and wants a system status overview
- Before a review session to know what needs attention
- User says "admin briefing", "morning briefing", or "what needs review?"
- Periodic check (daily or whenever returning after time away)

## What It Needs

- Admin API key (admin-only tools: \`review_suggestions\`, \`review_skill_suggestions\`, \`suggest_improvement\`)
- No Meta API or Google Ads connection needed

## What It Produces

- Count and summary of pending insight suggestions
- Count and summary of pending skill suggestions (with/without .md drafts)
- Bug reports and tool errors from the last 7 days
- Knowledge gaps (zero-result searches)
- Top search queries
- Prioritized action list

## Steps

1. **Pending Insight Suggestions**: Call \`review_suggestions\` with status \`pending\`. Report how many are waiting for review. For each, show the title, submitter, and a one-line summary of the insight.

2. **Pending Skill Suggestions**: Call \`review_skill_suggestions\` with status \`pending\`. Report how many are waiting. For each, show: name, description, data_sources, whether a .md draft was included, and the submitter. Flag separately: (a) skills with a full draft ready to deploy, (b) skills that still need a .md written.

3. **Recent Activity Summary**: Call \`suggest_improvement\` with \`days: 7\` to get:
   - Recent feedback submissions (especially \`bug_report\` and \`missing_knowledge\` categories)
   - Zero-result searches (topics users searched for but got no results)
   - Error patterns (tools that are failing)
   - Top search queries (what users are asking about most)

4. **Present the Briefing** in this format:

\`\`\`
## Admin Briefing — [today's date]

### Pending Insight Suggestions ([count])
- [title] — submitted by [name] on [date]
  Brief: [one-line summary]

### Pending Skill Suggestions ([count])
Ready to deploy (has .md draft):
- [name] — [description] — by [submitter]

Needs .md written:
- [name] — [description] — by [submitter]
  Idea: [one-line summary of user_description]

### Bug Reports ([count])
- [summary]

### Knowledge Gaps ([count])
- [topic/query that had no results]

### Tool Errors ([count])
- [tool]: [error pattern]

### Top Searches (last 7 days)
- [query] ([count]×)

### Recommended Actions
1. [Most urgent action based on the data above]
2. [Second action]
3. [Third action]
\`\`\`

5. **Prioritize actions**: Bug reports first. Then skill suggestions with drafts ready (low effort, high value — just commit + deploy). Then pending insight suggestions. Then knowledge gaps that align with top searches.

## Notes
- This briefing uses admin-only tools (\`review_suggestions\`, \`review_skill_suggestions\`, \`suggest_improvement\`). If these return errors, the user may not have admin access.
- Keep the briefing scannable — use bullet points, not paragraphs.
- For skill suggestions with a draft: use \`approve_skill_suggestion\` to get the final .md, then commit to \`skills/\`, run \`npm run build:prompts\`, and deploy.
- If everything is clean, say so briefly and suggest proactive actions like reviewing most-searched topics or writing Google Ads skills.
`,
  "attribution-analysis": `# Skill: Attribution & Conversion Validation

How to validate whether Meta-reported conversion numbers are real or inflated, using attribution window analysis and daily time-series data.

---

## When to Use This

- Comparing two campaigns with different CPI to rule out attribution as the cause
- Auditing a single campaign to understand conversion quality
- Investigating suspiciously high or low install numbers
- Validating whether view-through conversions are meaningful
- User asks "are these install numbers real?" or "why do my Meta numbers not match my MMP?"

## What It Needs

**Option A — Meta API connected**: Provide \`ad_account_id\`.

**Option B — CSV export** (no API needed):
- Go to **Meta Ads Manager** → **Campaigns** tab
- Date range: **Last 7 days**
- Click **Columns** → **Customize columns** → add: \`Results\`, \`Cost per result\`, \`1-day click conversions\`, \`7-day click conversions\`, \`1-day view conversions\`, \`7-day view conversions\`
- Export as CSV and paste below.
- Also helpful: export your MMP (AppsFlyer / Adjust) install data for the same period for cross-referencing.

## What It Produces

- Attribution window breakdown (click vs view, 1d vs 7d) showing how inflated the numbers may be
- View-through ratio (view conversions ÷ total conversions) — flags if VTC is propping up numbers
- Daily consistency check — flags days where conversions spike without matching impression/click movement
- MMP discrepancy analysis if MMP data is provided

---

## Knowledge Base Grounding

- **lp-pt-003** (Lauren Petrullo): "Contribution vs attribution — ads feed conversions without getting last-click credit. Killing low-converting ads can collapse the funnel."
- **jm-pt-001** (related): Attribution modeling considerations for cross-channel measurement.

---

## Step 1: Pull Multi-Window Attribution Data

\`\`\`
get_meta_insights(
  ad_account_id="act_123456789",
  level="campaign",
  fields="actions,cost_per_action_type,action_values",
  date_preset="last_7d"
)
\`\`\`

Note: For multi-window analysis, you may need direct API calls with \`action_attribution_windows=1d_click,7d_click,28d_click,1d_view\`.

Extract install counts for each window:

| Window | Installs | CPI |
|---|---|---|
| 1d_click (default) | | |
| 7d_click | | |
| 28d_click | | |
| 1d_view | | |

---

## Step 2: Check Delayed Conversion Uplift

Calculate:
- **1d → 7d uplift**: \`(7d_installs - 1d_installs) / 1d_installs × 100\`
- **7d → 28d uplift**: \`(28d_installs - 7d_installs) / 7d_installs × 100\`

### Interpretation

| 1d→7d Uplift | Signal |
|---|---|
| 10-20% | Healthy — users consider and return within a week |
| 3-5% | Low-intent — if they don't install immediately, they never will |
| >30% | Suspicious — investigate if attribution is overcounting |
| <1% | Either very direct-response creative, or very poor audience |

### Example from ROLA vs MX analysis
- ROLA: +14.0% (1d→7d) — healthy delayed consideration
- MX: +4.1% (1d→7d) — low-intent traffic confirmed

---

## Step 3: Analyze View-Through Ratio

Calculate: \`1d_view installs / 1d_click installs × 100\`

### Interpretation

| View-Through Ratio | Signal |
|---|---|
| 5-15% | Normal for app install campaigns |
| >25% | Possible attribution inflation — Meta counting impressions as conversions |
| <3% | Very click-driven campaign, view-through not a factor |

When comparing campaigns: if both have similar view-through ratios (~8-12%), attribution mechanics are comparable and the difference in CPI is real.

**Contribution vs attribution** [lp-pt-003]: Even if an ad has low direct conversions, it may be contributing to the funnel. View-through and assisted conversions indicate ads that are "feeding" the pipeline without getting last-click credit. Killing these ads can collapse the funnel.

---

## Step 4: Use Daily Time-Series for Consistency Check

\`\`\`
get_meta_insights(
  ad_account_id="act_123456789",
  level="campaign",
  fields="spend,impressions,actions",
  time_increment="1",
  date_preset="last_14d"
)
\`\`\`

Check:
- **Daily CPI consistency**: Stable CPI day-over-day = real performance. Wild swings = possible issues.
- **Install/impression ratio**: Should be relatively stable.
- **Weekend vs weekday patterns**: Normal to see dips; abnormal to see 5x swings.
- **Spend vs installs correlation**: If spend goes up but installs stay flat, Meta is buying junk inventory.

### Red flags in daily data
- Day with $800 spend and 34 installs next to day with $800 spend and 77 installs → inconsistent audience quality
- Steady spend but declining daily installs over 2 weeks → audience exhaustion
- Install spikes on specific days without corresponding spend increase → possible attribution lag

---

## Step 5: Cross-Reference with Creative Performance

\`\`\`
get_meta_insights(
  ad_account_id="act_123456789",
  level="ad",
  fields="ad_name,spend,impressions,actions",
  sort="spend_descending",
  limit=20
)
\`\`\`

For each top ad, check:
- Is the 1d_view count suspiciously close to 1d_click? (possible overcounting)
- Does the 7d_click show meaningful uplift over 1d_click? (delayed intent)
- Are there ads with very high spend but almost no 1d_click installs and lots of 1d_view? (view-through inflated)

---

## SKAN / iOS Attribution Notes

Meta does NOT expose raw SKAN data through the standard Insights API:
- \`skan_cv_app_install\`, \`skan_conversion\`, \`skan_campaign_id\`, \`skan_conversion_id\` → all return field validation errors
- \`signal_source_bucket\` breakdown → returns data but the field is always empty
- \`conversions\` field → no SKAN-specific action types appear

**What Meta does**: Receives SKAN postbacks from Apple and blends them into the modeled \`mobile_app_install\` numbers. The install counts you see are Meta's modeled estimates, not raw counts.

**To get raw SKAN postbacks**: You need an MMP (Adjust, AppsFlyer, Branch, Kochava) that receives SKAN postbacks independently from Apple.

---

## Output Template

\`\`\`markdown
## Attribution Analysis: [Campaign Name]

### Attribution Windows
| Window | Installs | CPI |
|---|---|---|
| 1d_click | X | $Y |
| 7d_click | X | $Y |
| 28d_click | X | $Y |
| 1d_view | X | $Y |

### Delayed Uplift: X% (1d→7d) — [healthy/low-intent/suspicious]
### View-Through Ratio: X% — [normal/inflated/minimal]
### Daily Consistency: [stable/unstable/declining]

### Contribution Warning [lp-pt-003]
[Note any ads that may be contributing to the funnel without getting direct credit]

### Conclusion
[Is the conversion data trustworthy? What does the attribution pattern reveal?]

### Knowledge Base References
- lp-pt-003
\`\`\`
`,
  "audience-composition": `# Skill: Audience Composition Report

Reveal who is actually converting and at what cost, by age and gender. Identifies mismatches between spend allocation and conversion efficiency.

---

## When to Use This

- User asks "who is converting?" or "what demographic is best for us?"
- CPA varies wildly and the cause isn't obvious at the campaign level
- User is deciding between App Promotion and Web Sales campaign types
- User wants to set up Value Rules based on age/gender
- User says "audience breakdown" or "demographic analysis"

## What It Needs

**Option A — Meta API connected**: Provide \`ad_account_id\`.

**Option B — CSV export** (no API needed):
- Go to **Meta Ads Manager** → **Campaigns** or **Ads** tab
- Date range: **Last 7 days**
- Click **Breakdown** → **By Delivery** → **Age** and then **Gender** (run two separate breakdowns, or use "Age and Gender" if available)
- Columns: \`Age\` / \`Gender\`, \`Spend\`, \`Impressions\`, \`Reach\`, \`CPM\`, \`CTR\`, \`Result\`, \`Cost per result\`
- Export both breakdowns as CSV and paste below.

## What It Produces

- Age × gender conversion efficiency heatmap
- Spend vs conversion share mismatch analysis
- Specific Value Rule recommendations (which demographic segments to bid up/down)
- Campaign type recommendation based on target demographic

---

## Knowledge Base Grounding

- **mb-li-010** (Marcus Burke): "Different creatives attract wildly different age demographics. Trial CVR by age: 18-24=18%, 25-34=26%, 35-44=32%, 45-54=44%, 55-64=48%, 65+=42%. Ads that attract older users are more valuable."
- **mb-li-006** (Marcus Burke): "App Promotion campaigns skew young (Reels-heavy). Web Sales campaigns skew older (Feed). Choose campaign type based on the demographic you want to reach."
- **mb-li-005** (Marcus Burke): "One price = one audience. Without offers for price-sensitive users, you'll never efficiently scale on Reels for younger demos."
- **mb-li-008** (Marcus Burke): "Value Rules let you set custom bid modifiers for age, gender, placement within the same broad-targeting ad set."
- **oh-li-003** (Olly Hudson): "Persona-based ads unlock new audiences 89% of the time."

---

## Procedure

### Step 1: Pull Age × Gender Breakdown

\`\`\`
get_meta_insights(
  ad_account_id="act_123456789",
  level="account",
  fields="spend,impressions,clicks,ctr,actions,cost_per_action_type",
  breakdowns="age,gender",
  date_preset="last_7d"
)
\`\`\`

### Step 2: Build Heatmap

Create an age × gender matrix showing:
- Spend per cell
- CPA per cell
- Conversions per cell
- % of total spend per cell

### Step 3: Analyze

1. **Which age groups get the most spend?**
2. **Which age groups have the best CPA?**
3. **Are high-value segments (35+) being reached?** [mb-li-010: they convert 2-3x better for subscription apps]
4. **Is budget concentrated on young demographics due to app campaign skew?** [mb-li-006]
5. **Spend vs efficiency mismatch**: flag if an age group gets >30% of spend but has CPA >1.5x average

### Step 4: Recommend

- If 35+ has better CPA but <20% of spend: "Consider adding Web Sales campaigns to reach older demographics on Feed [mb-li-006]. App Promotion campaigns are Reels-heavy and naturally skew young."
- If age CPA varies >2x: "Set up Value Rules with age-based bid modifiers to reflect actual conversion value [mb-li-008, mb-li-010]."
- If all spend goes to one age group: "Build persona-based creatives targeting different motivators to unlock new audiences [oh-li-003]."
- If younger demos have bad CPA: "Consider pricing variance — offer discounts for price-sensitive younger audiences [mb-li-005]."

---

## Output Template

\`\`\`markdown
## Audience Composition Report: [Account Name]

### Age × Gender Heatmap
| Age | Male Spend (CPA) | Female Spend (CPA) | Total Spend | Total CPA | % of Spend |
|-----|-------------------|---------------------|-------------|-----------|------------|
| 18-24 | $X ($Y) | $X ($Y) | $X | $Y | Z% |
| 25-34 | ... | ... | ... | ... | ... |
| 35-44 | ... | ... | ... | ... | ... |
| 45-54 | ... | ... | ... | ... | ... |
| 55-64 | ... | ... | ... | ... | ... |
| 65+   | ... | ... | ... | ... | ... |

### Key Findings
1. [Best performing segment]
2. [Worst performing segment]
3. [Biggest mismatch between spend and efficiency]

### Recommendations
1. [...]
2. [...]

### Knowledge Base References
- mb-li-010, mb-li-006, mb-li-005, mb-li-008, oh-li-003
\`\`\`
`,
  "audit-meta-account": `# Skill: Audit a Meta Ad Account

Run a structured audit of a Meta ad account against industry best practices from the knowledge base. Covers structure, creative, audience, bids, signals, and funnel in one pass.

---

## When to Use This

- User wants a full account health check ("audit my account", "review everything")
- Onboarding a new client or account
- Performance has been declining and the cause is unclear
- Before a large budget increase or campaign restructure
- Quarterly or semi-annual review

## What It Needs

**Option A — Meta API connected** (recommended for a full audit): Provide \`ad_account_id\`. The audit pulls structure + performance data across all levels.

**Option B — CSV export** (partial audit, structure + performance separately):
- **Campaigns**: Name, Objective, Status, Bid strategy, Budget, Spend (last 30 days), CPA, ROAS
- **Ad sets**: Name, Campaign, Status, Optimization goal, Targeting type, Budget, Spend, CPA
- **Ads**: Name, Ad set, Campaign, Status, Format, Spend, Frequency, CPA, Impressions (last 30 days)
- Export each level from Meta Ads Manager and paste all three below.
- Also note: conversion event being optimized, pixel setup (yes/no), any attribution window settings.

## What It Produces

- Findings across 6 dimensions: structure, creative, audience, bid strategy, signal quality, funnel
- Severity rating per finding (Critical / Recommended / Optional)
- Baseline metrics snapshot for future comparison
- Prioritized action plan (30/60/90 day)

---

## Knowledge Base Grounding

- **mb-li-002** (Marcus Burke): "Force deconsolidation — split creative types into separate ad sets to prevent self-cannibalization."
- **mb-li-003** (Marcus Burke): "Signal quality > signal volume. Train the algorithm on the event that matters most."
- **mb-li-006** (Marcus Burke): "App Promotion and Web Sales campaigns access different audiences. Scaled brands use both."
- **mb-li-008** / **mb-li-009** (Marcus Burke): Value Rules — bid differently on age, gender, placement within the same ad set.
- **mb-cd-001** (Marcus Burke): "EAC — web campaigns with in-app conversion feedback for subscription apps."
- **ds-pt-005** (Dara Saeed): "ASC campaigns need minimum 20 creatives for optimal performance."
- **lp-pt-001** (Lauren Petrullo): "Meta requires at least 25% creative difference for Andromeda."
- **lp-pt-002** (Lauren Petrullo): "Minimum 6 creatives per offering — 6 unique concepts or 2 concepts × 3 formats."
- **oh-li-001** (Olly Hudson): "Andromeda treats ads with similar first 3 seconds as identical."
- **oh-li-003** (Olly Hudson): "Persona-based ads unlock new audiences 89% of the time."
- **br-li-001** (Ben Radack): "CBO scaling with monthly winner rotation."
- **wk-tw-001** (William Kast): 4 diagnostic metric patterns for performance issues.

---

## Prerequisites

- Meta Marketing API access token (user provides via META_ACCESS_TOKEN)
- Access to MCP tools: \`get_meta_campaigns\`, \`get_meta_adsets\`, \`get_meta_ads\`, \`get_meta_insights\`, \`search_insights\`, \`get_insight\`
- Ad account ID (e.g., \`act_123456789\`)

## Procedure

### Step 1: Gather Account Structure

Use the Meta tools to pull structure:

\`\`\`
get_meta_campaigns(ad_account_id="act_123456789")
get_meta_adsets(ad_account_id="act_123456789")
get_meta_ads(ad_account_id="act_123456789")
\`\`\`

Record:
- Total active campaigns, ad sets, and ads
- Campaign objectives in use
- Bid strategies in use
- Budget distribution across campaigns
- Creative format distribution (video, image, carousel)

### Step 2: Gather Performance Metrics

Pull last 7 days of performance data (rate-limit safe):

\`\`\`
get_meta_insights(ad_account_id="act_123456789", level="campaign", date_preset="last_7d")
get_meta_insights(ad_account_id="act_123456789", level="account", breakdowns="age,gender", date_preset="last_7d")
get_meta_insights(ad_account_id="act_123456789", level="campaign", breakdowns="publisher_platform,platform_position", date_preset="last_7d")
\`\`\`

Record baseline metrics:
- Total spend, CPA, ROAS
- CPA by age group
- CPA by placement
- Top/bottom performing campaigns and ad sets

### Step 3: Analyze Against Best Practices

Use \`search_insights\` and \`get_insight\` to pull relevant knowledge. Evaluate:

#### Campaign Architecture
- [ ] Is the account over-consolidated (too few campaigns)? [mb-li-002]
- [ ] Are creative types mixed within ad sets (self-cannibalization risk)? [mb-li-002]
- [ ] Is there a mix of App Promotion and Web campaigns? [mb-li-006]
- [ ] Are campaign objectives aligned with business goals?
- [ ] Does the ASC campaign have 20+ creatives? [ds-pt-005]

#### Creative Strategy
- [ ] How many distinct creative concepts are active? Minimum 6 per offering [lp-pt-002]
- [ ] What's the ratio of video to static to carousel?
- [ ] Are creatives at least 25% visually different? [lp-pt-001]
- [ ] Do ads have different first 3 seconds (hooks)? [oh-li-001]
- [ ] Are there persona-based ads targeting different motivators? [oh-li-003]
- [ ] Is there a creative testing structure in place?

#### Audience & Targeting
- [ ] What's the age composition of spend and conversions? [mb-li-010]
- [ ] Are high-value age segments (35+) being reached?
- [ ] Is targeting broad or narrow? Is it appropriate?

#### Bid Strategy & Value Rules
- [ ] What bid strategies are in use?
- [ ] Are Value Rules configured? On which dimensions? [mb-li-008, mb-li-009]
- [ ] Are bid/cost caps set appropriately for the campaign type? [br-li-001]

#### Signal Quality
- [ ] What optimization events are campaigns using? [mb-li-003]
- [ ] Is the account optimizing for the deepest funnel event possible?
- [ ] Is CAPI configured for web campaigns?

#### Funnel Strategy
- [ ] Is the account app-only or does it include web funnels?
- [ ] For subscription apps: are there web-to-app campaigns reaching older demographics? [mb-li-006]
- [ ] Is EAC (External Attribution) being used? [mb-cd-001]

### Step 4: Score and Prioritize

Rate each category on a scale:
- **Green**: Well-optimized, minor tweaks only
- **Yellow**: Room for improvement, moderate impact
- **Red**: Significant issue, high-impact fix needed

### Step 5: Generate Output

Produce a structured output with:

\`\`\`json
{
  "ad_account_id": "act_123456789",
  "platform": "meta",
  "audit_date": "2026-03-10T00:00:00Z",
  "findings": {
    "campaign_architecture": {
      "score": "yellow",
      "issues": ["All creatives in single ad set — self-cannibalization risk [mb-li-002]"],
      "positives": ["Good campaign objective selection"]
    },
    "creative_strategy": { "score": "...", "issues": [], "positives": [] },
    "audience_targeting": { "score": "...", "issues": [], "positives": [] },
    "bid_strategy": { "score": "...", "issues": [], "positives": [] },
    "signal_quality": { "score": "...", "issues": [], "positives": [] },
    "funnel_strategy": { "score": "...", "issues": [], "positives": [] }
  },
  "baseline_metrics": {
    "total_spend_7d": 12000,
    "avg_cpa": 12.50,
    "cpa_by_age": { "18-24": 18.00, "25-34": 14.00, "35-44": 10.00, "45+": 8.50 },
    "top_placements": ["instagram_reels", "facebook_feed"],
    "active_campaigns": 5,
    "active_ad_sets": 12,
    "active_ads": 45
  },
  "recommendations": [
    {
      "priority": 1,
      "category": "campaign_architecture",
      "action": "Split creative types into separate ad sets to prevent self-cannibalization [mb-li-002]",
      "expected_impact": "high",
      "effort": "low",
      "related_insights": ["mb-li-002", "lp-pt-001"]
    }
  ]
}
\`\`\`

---

## Notes

- Always explain WHY each finding matters, referencing specific insight IDs from the knowledge base
- Prioritize recommendations by impact/effort ratio
- Compare the account's patterns against the knowledge base, not just generic best practices
- Use \`get_insight\` to read full insight text when citing specific recommendations
- This audit is a starting point — encourage the user to run it periodically to track improvement
`,
  "architecture-review": `# Skill: Campaign Architecture Review

Evaluate whether the account structure supports or limits scale. Structure-only analysis — no performance metrics needed, just campaign/adset/ad structure.

---

## When to Use This

- User is setting up Meta campaigns for the first time
- Scaling has stalled and the structure might be the reason
- User asks "is my account structured correctly?" or "should I consolidate?"
- Before a big budget increase — to verify the structure can handle it
- User mentions too many campaigns, ad sets, or campaigns with very few ads

## What It Needs

**Option A — Meta API connected**: Provide \`ad_account_id\`. Three API calls pull everything needed (no performance data required).

**Option B — Manual description or CSV**:
- Describe your campaign structure: how many active campaigns, what objectives, how many ad sets per campaign, how many ads per ad set, what bid strategies are in use
- Or export from **Meta Ads Manager** → **Campaigns**, **Ad Sets**, and **Ads** tabs separately:
  - Columns needed: \`Name\`, \`Status\`, \`Objective\` (campaigns), \`Bid strategy\`, \`Budget\`, \`Optimization goal\` (ad sets), \`Creative format\` (ads)
  - Export each level as CSV and paste below.

## What It Produces

- Structure scorecard across: consolidation, creative counts, campaign types, bid strategies, signal quality
- Specific issues with KB-grounded reasoning
- Recommended structural changes before next budget increase

---

## Knowledge Base Grounding

- **mb-li-002** (Marcus Burke): "Force deconsolidation — split creative types and messaging angles into separate ad sets to prevent self-cannibalization."
- **mb-li-003** (Marcus Burke): "Signal quality > signal volume. Always train the algorithm on the event that matters most."
- **mb-li-006** (Marcus Burke): "App Promotion and Web Sales campaigns access different audiences. Scaled brands use both."
- **mb-li-011** (Marcus Burke): "Breakthrough requires: creative diversity, architecture for scale, funnel expansion, organic amplification."
- **mb-cd-001** (Marcus Burke): "EAC — web campaigns with in-app conversion feedback for subscription apps."
- **ds-pt-005** (Dara Saeed): "ASC campaigns need minimum 20 creatives for optimal performance."
- **br-li-001** (Ben Radack): "CBO scaling with monthly winner rotation — new ad set each month for that month's proven winners."
- **br-li-002** (Ben Radack): "Zombie campaign — low cost cap CBO where every failed creative gets a second chance."
- **lp-pt-001** (Lauren Petrullo): "Meta requires at least 25% creative difference for Andromeda."
- **lp-pt-002** (Lauren Petrullo): "Minimum 6 creatives per offering — 6 unique concepts or 2 concepts × 3 formats."

---

## Procedure

### Step 1: Pull Account Structure

3 API calls — structure only, no insights:

\`\`\`
get_meta_campaigns(ad_account_id="act_123456789")
get_meta_adsets(ad_account_id="act_123456789")
get_meta_ads(ad_account_id="act_123456789")
\`\`\`

### Step 2: Run Architecture Checks

| Check | What | Flag | Source |
|-------|------|------|--------|
| Over-consolidation | All ads in 1-2 campaigns | ⚠ Self-cannibalization risk | mb-li-002 |
| Creative type mixing | Video + static + carousel in same ad set | ⚠ Prevents unique reach per format | mb-li-002 |
| Creative count | <6 ads per ad set / <20 in ASC | ⚠ Insufficient for Andromeda | lp-pt-002, ds-pt-005 |
| Campaign type diversity | App-only, no web campaigns | ⚠ Missing older demographics | mb-li-006, mb-li-011 |
| Optimization event | Upper-funnel event (installs) when deeper events exist | ⚠ Signal quality issue | mb-li-003 |
| Bid strategy | No cost caps on scaling campaigns | ⚠ No spend protection | br-li-001 |
| EAC | No web2app campaigns for subscription app | 💡 Opportunity | mb-cd-001 |
| Zombie campaign | No low-cap recovery campaign | 💡 Opportunity | br-li-002 |
| Creative similarity | Ads with likely similar first 3 seconds | ⚠ Andromeda treats them as identical | oh-li-001, lp-pt-001 |

### Step 3: Score and Prioritize

Rate each check:
- ✅ **Good**: Well-structured
- ⚠ **Issue**: Problem that limits scale
- 💡 **Opportunity**: Missing capability that could unlock growth

---

## Output Template

\`\`\`markdown
## Campaign Architecture Review: [Account Name]

### Structure Summary
- Active campaigns: X | Ad sets: Y | Ads: Z
- Campaign types: [list]
- Bid strategies: [list]

### Architecture Checks
| Check | Status | Finding | Action | Source |
|-------|--------|---------|--------|--------|
| Over-consolidation | ⚠ | All 30 ads in 1 campaign | Split by creative type into separate ad sets | mb-li-002 |
| Creative count | ⚠ | Avg 3 ads per ad set | Add more concepts — minimum 6 per offering | lp-pt-002 |
| Campaign type diversity | ⚠ | App-only | Add Web Sales campaigns for older demos | mb-li-006 |
| ... | ... | ... | ... | ... |

### Opportunities
1. **EAC campaigns** [mb-cd-001]: Web campaigns with in-app conversion feedback for subscription apps — reaches demographics that App Promotion misses.
2. **Zombie campaign** [br-li-002]: Low cost cap CBO where failed creatives get a second chance — recovers value from retired ads.

### Recommended Architecture
[Proposed campaign structure based on findings]

### Knowledge Base References
- mb-li-002, mb-li-003, mb-li-006, mb-li-011, mb-cd-001, ds-pt-005, br-li-001, br-li-002, lp-pt-001, lp-pt-002
\`\`\`
`,
  "campaign-comparison": `# Skill: Campaign Comparison

Reusable step-by-step framework for comparing any two Meta campaigns to identify why one outperforms the other.

---

## When to Use This

- User points to two campaigns with different CPIs and asks why
- User wants to understand what makes a winning campaign different
- Before scaling one campaign and pausing another — validate the reason
- User says "campaign A is doing better than B, what's different?"
- Testing a new campaign structure against an existing one

## What It Needs

**Option A — Meta API connected**: Provide \`ad_account_id\` and optionally the two \`campaign_id\` values. If IDs aren't provided, the skill will list campaigns and ask you to pick two.

**Option B — CSV export** (no API needed):
- Export from **Meta Ads Manager** → **Campaigns** tab, then drill into each campaign for its ad sets and ads
- For each campaign export: \`Campaign name\`, \`Objective\`, \`Bid strategy\`, \`Budget type\`, \`Budget\`, \`Start date\`, \`Spend\`, \`Impressions\`, \`Frequency\`, \`CPM\`, \`CTR\`, \`CPA\`, \`Conversions\`
- Also export **Ad sets** for each campaign: \`Ad set name\`, \`Targeting type\`, \`Optimization goal\`, \`Bid strategy\`, \`Budget\`, \`Placements\`, \`Spend\`, \`CPA\`
- Paste both campaign exports below, labeled by campaign name.

## What It Produces

- Side-by-side comparison across: settings, targeting, creative count/format, performance metrics
- Root cause identification for the performance gap
- Specific hypothesis for what's driving the difference

---

## Knowledge Base Grounding

- **wk-tw-001** (William Kast): 4 diagnostic metric patterns — Frequency↑+CPA↑ (fatigue), CPM↑+CPA↑ (saturation), CPA↑+CVR↓ (LP mismatch), CTR↓+CPA↑ (creative fatigue).
- **lp-pt-003** (Lauren Petrullo): "Contribution vs attribution — ads feed conversions without getting last-click credit."
- **jl-pt-004** (Jon Loomer): "Don't turn off underperforming ads if aggregate performance is good — they may play a halo role."
- **oh-li-001** (Olly Hudson): "Andromeda treats ads with similar first 3 seconds as identical."

---

## Step 1: Pull Campaign Settings Side-by-Side

\`\`\`
get_meta_campaigns(ad_account_id="act_123456789")
\`\`\`

Then filter for the two campaigns being compared.

Compare: objective, bid strategy, daily budget, buying type, how long each has been running.

**Watch for**: Budget set at campaign level vs ad set level. One campaign may have 2x the budget — that alone can explain saturation effects.

---

## Step 2: Pull Ad Set Targeting & Placement Differences

\`\`\`
get_meta_adsets(ad_account_id="act_123456789", campaign_id="CAMPAIGN_A_ID")
get_meta_adsets(ad_account_id="act_123456789", campaign_id="CAMPAIGN_B_ID")
\`\`\`

Compare:
- **Geo-targeting**: Single country vs multi-country
- **Placements**: Which publisher_platforms and positions are enabled
- **Audience**: Age range, exclusions, Advantage+ settings
- **Bid amount**: Same cost cap? Different?

**Watch for**: Extra placements in the underperformer (instream_video, reels_overlay, threads are common waste placements for iOS app installs).

---

## Step 3: Pull Aggregate Insights

\`\`\`
get_meta_insights(
  ad_account_id="act_123456789",
  level="campaign",
  fields="campaign_id,campaign_name,spend,impressions,clicks,cpm,cpc,ctr,reach,frequency,actions,cost_per_action_type",
  date_preset="last_7d"
)
\`\`\`

Build comparison table:

| Metric | Campaign A | Campaign B | Ratio |
|---|---|---|---|
| Spend | | | |
| Impressions | | | |
| CTR | | | |
| CPM | | | |
| Frequency | | | |
| Installs | | | |
| **CPI** | | | |

**Apply Kast's diagnostic framework** [wk-tw-001] to interpret the metric differences:
- If Campaign B has higher CPM AND higher CPA → audience saturation or poor engagement
- If Campaign B has declining CTR AND higher CPA → creative fatigue
- If Campaign B has higher CPA AND lower CVR → ad-to-landing-page mismatch

---

## Step 4: Run Funnel Analysis

Calculate conversion rates at each step:

| Step | Campaign A | Campaign B |
|---|---|---|
| Impressions | | |
| → Click Rate | | |
| → Install Rate from Impressions | | |

**Watch for**: If Campaign B sends MORE people to the app store but converts at a lower rate, Meta is sending low-intent traffic.

---

## Step 5: Break Down by Placement

\`\`\`
get_meta_insights(
  ad_account_id="act_123456789",
  level="campaign",
  fields="spend,impressions,cpm,ctr,actions,cost_per_action_type",
  breakdowns="publisher_platform,platform_position",
  date_preset="last_7d"
)
\`\`\`

For each placement, calculate CPI. Compare:
- Which placements exist in one campaign but not the other?
- What's the CPI range? Tight ($3-$6) = healthy. Wide ($8-$84) = waste.
- How much spend goes to the worst placements?

See \`skills/placement-audit.md\` for the full placement audit methodology.

---

## Step 6: Break Down by Country (Multi-Geo Campaigns)

\`\`\`
get_meta_insights(
  ad_account_id="act_123456789",
  level="campaign",
  breakdowns="country",
  date_preset="last_7d"
)
\`\`\`

**Watch for**: One country eating the majority of budget with poor results.

---

## Step 7: Compare Same Creatives Across Campaigns

\`\`\`
get_meta_insights(
  ad_account_id="act_123456789",
  level="ad",
  fields="ad_name,adset_name,spend,impressions,actions,cost_per_action_type",
  sort="spend_descending",
  limit=50
)
\`\`\`

Match ads by creative name across campaigns.

If the same creatives consistently perform 2-3x worse in one campaign, the problem is **not** creative quality — it's the campaign environment.

**Check for creative similarity** [oh-li-001]: Are ads in the underperforming campaign all variations of the same concept (similar first 3 seconds)? Andromeda treats them as identical, reducing effective creative diversity.

**Attribution contribution warning** [lp-pt-003, jl-pt-004]: Before pausing underperforming ads, check if aggregate ad set performance is good. Low-converting ads may be contributing to the funnel without getting last-click credit.

---

## Step 8: Identify Root Causes

Use this decision tree:

1. **Same creatives worse in one campaign?** → Problem is campaign-level, not creative
2. **Funnel leaks at app store step?** → Low-intent traffic
3. **Bad placements burning budget?** → Placement waste
4. **One campaign spends 2x+ in single market?** → Budget saturation
5. **CPM cheap but CPI high?** → Cheap impressions ≠ cheap installs

Apply Kast's diagnostic framework [wk-tw-001] to determine which pattern matches, then follow the recommended action for that pattern.

---

## Output Template

\`\`\`markdown
## Campaign Comparison: [A] vs [B]

### Setup Differences
- [Key difference 1]
- [Key difference 2]

### Performance Gap
- CPI: $X vs $Y (Z× difference)

### Diagnosis [per wk-tw-001 framework]
- [Pattern identified and what it means]

### Root Causes
1. [Primary cause]
2. [Secondary cause]

### Recommended Actions
1. [Action 1]
2. [Action 2]

### Knowledge Base References
- wk-tw-001, lp-pt-003, jl-pt-004, oh-li-001
\`\`\`
`,
  "creative-performance": `# Skill: Creative Performance Report

Categorize every active ad by health status and provide specific next steps per category, grounded in knowledge base insights.

---

## When to Use This

- User asks "which ads are working?" or "what should I pause?"
- User wants to know which creatives to scale, keep, or replace
- Before planning a new creative batch
- CPA is rising and the cause might be at the ad level
- User says "creative audit" or "ad performance"

## What It Needs

**Option A — Meta API connected**: Provide \`ad_account_id\`.

**Option B — CSV export** (no API needed):
- Go to **Meta Ads Manager** → **Ads** tab
- Date range: **Last 7 days**
- Columns: \`Ad name\`, \`Ad set name\`, \`Campaign name\`, \`Delivery\`, \`Spend\`, \`Impressions\`, \`Frequency\`, \`CPM\`, \`CTR (link)\`, \`CPC\`, \`Result\` (your conversion event), \`Cost per result\`
- Export as CSV and paste below.
- Also note your target CPA so ads can be benchmarked against it.

## What It Produces

- Ad-level health table with category: Scaling / Promising / Contributing / Fatiguing / Dead weight
- Specific recommended action per ad
- Creative diversity assessment (format coverage, minimum 6 concepts check)

---

## Knowledge Base Grounding

- **ds-pt-001** (Dara Saeed): "Only optimize based on primary metrics (CPA, ROAS). A low CTR or high CPM doesn't mean an ad is failing if the CPA is profitable."
- **ds-pt-004** (Dara Saeed): "Meta has determined that scaling 'more profitable' low-spend ads further would degrade performance. Don't try to force spend to them."
- **jl-pt-004** (Jon Loomer): "In BAU campaigns, don't turn off underperforming ads if aggregate performance is good. They may play a halo role."
- **lp-pt-003** (Lauren Petrullo): "Contribution vs attribution — ads feed conversions without getting last-click credit. Killing low-converting ads can collapse the funnel."
- **vs-nt-001** (Virendra Shekhawat): "Meta auto-shifts spend when creative degrades."
- **mb-li-001** (Marcus Burke): "Creative unlocks scale, iterations maintain it. Only genuinely new concepts unlock new audiences."
- **oh-li-001** (Olly Hudson): "Andromeda treats ads with similar first 3 seconds as identical."
- **lp-pt-001** (Lauren Petrullo): "Meta requires at least 25% creative difference."
- **lp-pt-002** (Lauren Petrullo): "Minimum 6 creatives per offering — 6 unique concepts or 2 concepts × 3 formats."

---

## Procedure

### Step 1: Pull Ad-Level Insights

\`\`\`
get_meta_insights(
  ad_account_id="act_123456789",
  level="ad",
  fields="ad_id,ad_name,adset_id,adset_name,spend,impressions,clicks,ctr,cpm,frequency,actions,cost_per_action_type",
  date_preset="last_7d",
  sort="spend_descending",
  limit=50
)
\`\`\`

### Step 2: Determine Target CPA

Ask the user for their target CPA, or calculate account average CPA from the data.

### Step 3: Categorize Each Ad

| Category | Criteria | Action (grounded in KB) |
|----------|----------|------------------------|
| **Scaling** | High spend (>10% of total), CPA ≤ target | Let it run. Don't micro-optimize. Extract creative learnings for new concepts [mb-li-001]. |
| **Promising** | Low spend, CPA ≤ target | Don't force more spend — Meta has determined scaling would degrade it [ds-pt-004]. Analyze what makes it work and apply learnings to new ads. |
| **Contributing** | Getting impressions, low/no conversions, but aggregate ad set is healthy | Likely playing a halo role [jl-pt-004, lp-pt-003]. Do NOT pause. Meta shows it for a reason. |
| **Fatiguing** | Frequency >3, CTR declining or CPA rising | Prepare replacement with genuinely different visuals [oh-li-001, lp-pt-001]. Meta will auto-shift spend [vs-nt-001]. |
| **Dead weight** | High spend (>5% of total), CPA >2x target, for >7 days | Consider pausing only if aggregate ad set performance is also bad [jl-pt-004]. |

### Step 4: Creative Diversity Assessment

- How many genuinely different concepts are running? (not just variations)
- Are there format differences (video/static/carousel) or just copy changes? [lp-pt-001: need 25% visual difference]
- Minimum 6 creatives per offering [lp-pt-002]

---

## Output Template

\`\`\`markdown
## Creative Performance Report: [Account Name]

### Summary
- X ads analyzed across Y ad sets
- Total spend: $X | Average CPA: $Y
- Z scaling | W promising | V contributing | U fatiguing | T dead weight

### Ad Categories
#### 🟢 Scaling (X ads, $Y spend)
| Ad | Spend | CPA | CTR | Notes |
|----|-------|-----|-----|-------|

#### 💡 Promising (X ads, $Y spend)
| Ad | Spend | CPA | CTR | Notes |
|----|-------|-----|-----|-------|

#### 🔵 Contributing (X ads, $Y spend)
| Ad | Spend | Impressions | Conversions | Ad Set Health |
|----|-------|-------------|-------------|---------------|

#### 🟡 Fatiguing (X ads, $Y spend)
| Ad | Spend | Freq | CTR Trend | CPA | Diagnosis |
|----|-------|------|-----------|-----|-----------|

#### 🔴 Dead Weight (X ads, $Y spend)
| Ad | Spend | CPA | vs Target | Ad Set CPA |
|----|-------|-----|-----------|------------|

### Creative Diversity
- Unique concepts: X
- Format mix: Y% video, Z% static, W% carousel
- [Assessment and gaps]

### Recommendations
1. [...]

### Knowledge Base References
- ds-pt-001, ds-pt-004, jl-pt-004, lp-pt-003, vs-nt-001, mb-li-001, oh-li-001, lp-pt-001, lp-pt-002
\`\`\`
`,
  "google-architecture-review": `# Skill: Google App Campaign Architecture Review

Structure-only audit of Google App Campaigns — checks whether campaign setup, ad group structure, bidding approach, and audience exclusions support efficient scaling.

---

## When to Use This

- User is setting up Google App Campaigns for the first time
- User's campaigns are running but results are inconsistent or below expectation
- User wants to sanity-check their account structure before scaling budget
- After onboarding to Google Ads from another platform
- User mentions running only one campaign type (CPA only, or tROAS only)

## What It Needs

**Option A — Google Ads connected** (structure only, no performance data needed):

\`\`\`
get_google_ads_campaigns(customer_id="123-456-7890")
get_google_ad_groups(customer_id="123-456-7890", campaign_id="...")
\`\`\`

**Option B — CSV / manual input:** Export from Google Ads UI:
- **Campaigns report**: Columns: \`Campaign\`, \`Campaign type\`, \`Bidding strategy\`, \`Target CPA / Target ROAS\`, \`Budget\`, \`Status\`, \`Start date\`
- **Ad groups report**: Columns: \`Campaign\`, \`Ad group\`, \`Status\`, \`Assets count (video/image/text)\`
- **Audiences**: Go to Audiences → check which audience segments are added as exclusions

Paste both exports, or describe your campaign structure in plain text.

## What It Produces

- Structural assessment across 5 dimensions: campaign types, bid strategies, ad group structure, audience exclusions, and asset coverage
- Specific gaps with KB-grounded reasoning
- Prioritized list of structural changes to make before scaling

---

## Knowledge Base Grounding

- **ab-pt-001** (Ashley Black): "Android is a must — Play Store is uniquely high-intent inventory. iOS requires $500+/day minimum, $1,000+/day for subscription apps. Don't run iOS on Google if budget is under that."
- **ab-pt-009** (Ashley Black): "Google does not auto-exclude existing users — you must manually add your existing user list as an audience exclusion in every campaign. Without this, you're paying for re-installs."
- **ab-pt-012** (Ashley Black): "Run CPA and tROAS campaigns side by side. tROAS alone struggles to scale — it optimizes for revenue quality but limits volume. CPA drives install volume, tROAS maximizes value from the best users."
- **ab-pt-007** (Ashley Black): "Algorithms get fatigued. Campaigns running > 90 days with stagnant performance often need a full duplicate (new campaign) to reset the algorithm's optimization state."
- **gg-gem-1293** (ex-Googler): "Add new ad groups rather than increasing bids to scale — new ad groups open new inventory pockets without disturbing the existing campaign's optimization."
- **ab-pt-011** (Ashley Black): "tROAS requires Firebase integration, high event volume (10+ revenue events/day), and risk tolerance. Don't set up tROAS without these prerequisites."
- **ab-pt-019** (Ashley Black): "Google needs 50 installs/day or 10 target events/day to optimize. Below that, the algorithm is guessing. Consolidate campaigns rather than spreading budget too thin."

---

## Procedure

### Step 1: Pull Campaign and Ad Group Structure

**If API connected:**

\`\`\`
get_google_ads_campaigns(customer_id="123-456-7890")

# For each campaign, pull ad groups
get_google_ad_groups(
  customer_id="123-456-7890",
  campaign_id="[campaign_id]"
)
\`\`\`

**If manual:** Use the CSV exports or description the user provided.

### Step 2: Assess Campaign Type Coverage

Check which campaign types are active:

| Campaign Type | What It Does | Check |
|---------------|--------------|-------|
| App installs (CPA) | Drives install volume, optimizes for cost per install | Should be the base for all accounts |
| App engagement | Re-engages existing users | Separate from install campaigns |
| tROAS (target ROAS) | Optimizes for revenue quality | Requires Firebase + 10+ events/day |

**Flag if:**
- No Android campaign → missing Play Store (highest-intent inventory) [ab-pt-001]
- iOS budget < $500/day → algorithm won't have enough signal [ab-pt-001]
- Only tROAS, no CPA campaign → volume will be constrained [ab-pt-012]
- Only CPA, no tROAS → may be leaving high-value user revenue on the table [ab-pt-012]

### Step 3: Check Ad Group Structure

Best practice: each ad group = one creative angle or audience segment. This lets Google learn what works without blending signals.

**Flag if:**
- Single ad group per campaign with all assets mixed → no learnings isolation
- Ad groups running > 90 days with no new assets added → creative pool is stale [ab-pt-007]
- Ad groups with < 3 video assets on iOS campaigns → missing YouTube Shorts and in-stream inventory [ab-pt-003]
- Ad groups with < 5 text asset variants → keyword coverage is thin [ab-pt-004]

### Step 4: Check Audience Exclusions

**Critical check**: Is the existing user base excluded from install campaigns?

Google does NOT do this automatically. Without exclusions, you're buying re-installs — wasted budget and inflated install numbers.

**What to check:**
- Is a Customer Match list (existing users) excluded from all install campaigns?
- Is a remarketing list (users who installed but didn't convert) used for engagement campaigns?

**Flag if:** No audience exclusions on any install campaign → almost certain budget waste [ab-pt-009].

### Step 5: Check Bidding Setup

| Signal | Issue |
|--------|-------|
| CPA campaign, < 50 installs/day | Budget too spread out; consider consolidating campaigns |
| tROAS campaign, no Firebase integration | tROAS can't work without Firebase events [ab-pt-011] |
| tROAS campaign, < 10 revenue events/day | Insufficient signal; tROAS will underperform [ab-pt-011] |
| Bids changed > 20% recently | Risk of campaign destabilization [ab-pt-006] |

### Step 6: Output

\`\`\`
## Google Architecture Review — [date]

### Campaign Structure Overview
- [N] active campaigns: [list types]
- [N] total ad groups
- Budget concentration: [top campaign name] accounts for X% of total spend

### Critical Issues (Fix Before Scaling)

🔴 **No audience exclusions on install campaigns**
Existing users are not excluded — Google is buying re-installs. Add your existing user Customer Match list as an exclusion on all install campaigns immediately. [ab-pt-009]

🔴 **iOS budget below algorithm threshold**
iOS campaign is running at $X/day — below the $500/day minimum for Google to optimize. Either increase budget or pause iOS until budget allows. [ab-pt-001]

### Structural Gaps

🟡 **No tROAS campaign alongside CPA**
You're maximizing install volume but not optimizing for your highest-value users. Add a tROAS campaign once you reach 10+ revenue events/day in Firebase. [ab-pt-012]

🟡 **Single ad group per campaign**
No creative angle isolation. Add a second ad group with a different creative angle to let Google learn what resonates differently. [gg-gem-1293]

### What's Working Well
- [positives]

### Recommended Actions (Priority Order)
1. Add audience exclusions (today — zero cost, immediate budget efficiency gain)
2. ...
\`\`\`
`,
  "google-asset-performance": `# Skill: Google Asset Performance Report

Categorize every active asset (video, image, text) by health status and provide specific next steps — grounded in how Google actually scores and serves assets, not how the UI reports them.

---

## When to Use This

- User asks "which Google creatives are working?"
- CPI is rising and creative fatigue is suspected
- User wants to know what to pause, keep, or replace in Google Ads
- User is planning a new creative batch and wants to understand gaps
- After running \`google-campaign-health\` and a campaign is flagged as degrading

## What It Needs

**Option A — Google Ads connected:**

\`\`\`
get_google_assets(customer_id="123-456-7890", campaign_id="...")
get_google_asset_fatigue(customer_id="123-456-7890", campaign_id="...")
\`\`\`

**Option B — CSV export:** Export from Google Ads UI:
- Go to **Ads & Assets** → **Assets** tab
- Columns: \`Asset\`, \`Asset type\`, \`Campaign\`, \`Ad group\`, \`Performance label\` (Low/Good/Best/Learning), \`Impressions\`, \`Clicks\`, \`Conversions\`, \`Cost\`, \`CPI\`
- Also export the **Ad groups** report with the same date range for context
- Date range: last 14 days. Export as CSV and paste below.

## What It Produces

- Asset-level health table with category per asset
- Creative gap analysis (which formats/placements are underserved)
- Specific assets to pause, test differently, or replace
- Next creative batch recommendations grounded in iOS/Android traffic split

---

## Knowledge Base Grounding

- **ab-pt-008** (Ashley Black): "Ignore Google's built-in creative performance label — it measures scalability potential, not value delivered. A 'Low' asset may still be driving installs efficiently."
- **ab-pt-003** (Ashley Black): "iOS: ~60% video traffic (YouTube-heavy). Android: ~30% video (Play Store absorbs most traffic with text/image). Creative priorities differ by platform."
- **ab-pt-004** (Ashley Black): "Text assets function like keywords — Google indexes them against search queries. Different keywords have drastically different CPMs. Analyze cost by text asset."
- **gg-gem-1295** (ex-Googler): "Use IPM (installs per 1000 impressions) to compare assets of the same type — it normalizes for spend differences."
- **gg-gem-1178** (community): "You need different creative for each of Google's inventory types — what works on YouTube Shorts doesn't work on Play Store browse or AdMob."
- **ab-pt-015** (Ashley Black): "Don't copy Meta creative strategy to Google — Meta optimizes for scroll-stop, Google optimizes for intent-match. Different hooks, different pacing."
- **gg-gem-1181** (community): "In Conversion settings you can opt-in for 6-second bumper ads — a separate format that can unlock new inventory."

---

## Procedure

### Step 1: Pull Asset Data

**If API connected:**

\`\`\`
get_google_assets(
  customer_id="123-456-7890",
  campaign_id="[campaign_id]"
)

get_google_asset_fatigue(
  customer_id="123-456-7890",
  campaign_id="[campaign_id]"
)
\`\`\`

**If CSV:** Use the assets export the user pasted.

### Step 2: Determine Target CPI

Ask the user for their target CPI, or calculate account average from the data.

### Step 3: Categorize Each Asset

**Critical rule**: Do not use Google's "Performance label" (Low/Good/Best) as the primary signal [ab-pt-008]. Use actual CPI and impression share instead.

| Category | Criteria | Action |
|----------|----------|--------|
| **Top performer** | CPI ≤ target, high impressions (>15% of campaign total) | Keep running. Extract what makes it work — hook, format, message angle. |
| **Efficient but limited** | CPI ≤ target, low impressions (<5%) | Google has deprioritized it — likely similar to a higher-spend asset [oh-li-001 analogy]. Don't force it. Analyze what's different. |
| **Learning** | < 7 days live or < 500 impressions | Too early to judge. Leave running. |
| **Fatiguing** | IPM declining over last 7 days, CPI rising | Flag for replacement. Don't pause yet — wait until a replacement is ready [ab-pt-007 analogy]. |
| **Underperforming** | CPI > 2× target for > 14 days, significant impressions | Candidate for pause. Check if it's covering a unique placement before pausing. |
| **Low label, efficient** | Google says "Low" but CPI ≤ target | Keep it — Google's label means it won't scale further, not that it's wasting money [ab-pt-008]. |

### Step 4: Format Gap Analysis

Check coverage across asset types, grounded in platform traffic split:

**For iOS campaigns** (60% video traffic):
- Do you have videos in multiple durations: 6s, 10s, 20s, 30s, 30s+?
- Do you have portrait/vertical videos for YouTube Shorts?
- Fewer than 3 video variants = high fatigue risk

**For Android campaigns** (30% video, 70% text/image):
- Do you have landscape images (1.91:1)?
- Do you have 5 distinct text headline assets with different keyword angles [ab-pt-004]?
- Are text assets using specific search terms (pain points, features, long-tail) rather than generic copy?

**Bumper ads**: Are 6-second bumpers enabled? If not, you may be missing inventory [gg-gem-1181].

### Step 5: Text Asset Keyword Analysis

For each text asset with significant impressions:
- What keyword/intent does it signal?
- Is the CPM or CPI noticeably different from other text assets?
- Flag high-CPM text assets (likely expensive keyword territory) vs low-CPM high-performers

### Step 6: Output

\`\`\`
## Google Asset Performance — [campaign] — [date range]

### Asset Health Summary

| Asset | Type | CPI | vs Target | IPM | Category |
|-------|------|-----|-----------|-----|----------|
| [name] | Video 30s | $2.10 | -15% | 4.2 | Top performer |
| [name] | Text | $4.80 | +92% | 1.1 | Underperforming |

### Creative Gaps
- iOS: Missing portrait video for YouTube Shorts (high-traffic placement)
- Android: Only 2 text asset variants — recommend 3 more with different keyword angles

### Assets to Pause
- [name]: CPI $4.80 (+92% above target) for 18 days. Confirm it's not the only asset covering a key placement before pausing.

### Next Batch Recommendations
1. [Format]: [rationale grounded in gap analysis]
2. ...

### Note on Google's Labels
[X] assets are labeled "Low" by Google but have CPI at or below target — these are working ads that Google has chosen not to scale further. Do not pause them based on the label alone.
\`\`\`
`,
  "google-bid-strategy": `# Skill: Google Bid Strategy Advisor

Evaluate whether the current bid strategy setup is correct, whether the algorithm has sufficient signal to optimize, and how to safely adjust bids when performance needs to change.

---

## When to Use This

- User wants to switch from CPA to tROAS (or vice versa)
- User's CPI is above target and they want to lower bids
- User wants to scale and is considering raising bids or budgets
- User is setting up Google App Campaigns for the first time and asking which bid strategy to use
- tROAS campaign is underperforming or not spending its budget
- User asks "should I increase my bids?"

## What It Needs

**Option A — Google Ads connected:**

\`\`\`
get_google_ads_campaigns(customer_id="123-456-7890")
get_google_insights(
  customer_id="123-456-7890",
  date_range="LAST_30_DAYS",
  level="CAMPAIGN",
  metrics=["conversions","cost_micros","cost_per_conversion","all_conversions_value"]
)
\`\`\`

**Option B — Manual input / CSV:** Ask the user for:
- Current bid strategy per campaign (Target CPA / Target ROAS)
- Current target CPA value or target ROAS value
- Last 30-day actuals: daily installs average, daily revenue events average (if tROAS), actual CPI or ROAS
- Firebase integration: yes/no
- Recent bid changes: when and by how much

## What It Produces

- Assessment of whether each campaign's bid strategy is appropriate for its signal volume
- Specific bid adjustment recommendations with safe change sizes
- Go/no-go verdict on switching to tROAS
- Scaling path if user wants to grow spend

---

## Knowledge Base Grounding

- **ab-pt-006** (Ashley Black): "Never adjust bids or budgets more than 20% in a single day. Larger changes cause campaigns to tank and struggle to recover. This is Google's own guidance — believe it."
- **ab-pt-019** (Ashley Black): "Google recommends 50 installs/day or 10 target events/day. Aim for double (100 installs/day or 20 events/day). Below threshold = the algorithm is guessing, not learning."
- **ab-pt-010** (Ashley Black): "tROAS campaigns: start your target 20%+ below your actual ROAS target. Use 7-day conversion windows. Give it 2–3 weeks to exit the learning phase before evaluating."
- **ab-pt-011** (Ashley Black): "tROAS requires Firebase integration, high event volume (10+ revenue events/day), and risk tolerance. Don't set up tROAS without all three — it will underperform and you'll incorrectly blame the strategy."
- **ab-pt-012** (Ashley Black): "Run CPA and tROAS campaigns side by side. tROAS alone struggles to scale — it chases quality over volume. CPA provides the volume floor, tROAS extracts value from the best users."
- **ab-pt-020** (Ashley Black): "tROAS campaigns tend to have higher CPMs but deliver better-quality traffic. The higher CPI is often justified by better retention and monetization — measure downstream, not just install cost."
- **gg-gem-1218** (community): "When increasing bids, use the hamburger approach — small increase, let it stabilize, small increase again. Don't jump to your target bid in one move."
- **gg-gem-1293** (ex-Googler): "Scaling via new ad groups is safer than raising bids — new ad groups open new inventory pockets without disturbing existing campaign optimization signals."
- **gg-gem-1215** (community): "A high ROAS target means a longer ramp-up period. If you set tROAS too aggressively, the campaign will underspend during learning."

---

## Procedure

### Step 1: Gather Current Setup

Collect:
- Bid strategy per campaign (Target CPA or Target ROAS)
- Current target values
- Actual 30-day performance (CPI, daily install volume, daily revenue events if tROAS)
- Firebase connected: yes/no
- Any bid changes in the last 14 days

### Step 2: Check Algorithm Signal Sufficiency

For each campaign:

| Volume | Assessment |
|--------|------------|
| < 50 installs/day (CPA) | Below threshold — algorithm can't optimize. Must consolidate or increase budget before adjusting bids. |
| 50–100 installs/day | Functional but fragile. Any bid change will disrupt learning. Be conservative. |
| > 100 installs/day | Sufficient signal. Standard 20% bid change rule applies. |
| < 10 revenue events/day (tROAS) | tROAS cannot function. Switch to CPA or add Firebase events [ab-pt-011]. |
| > 10 revenue events/day (tROAS) | Functional. Evaluate ROAS target vs actual. |

### Step 3: Evaluate CPA Bid Setting

If actual CPI is above target CPA:
- **First check**: Is it a volume problem (< 50 installs/day)? Fix volume before touching bids.
- **If volume is fine**: Calculate safe bid reduction. Max 20% down from current [ab-pt-006].
- **Wait time**: 7–14 days after a change before evaluating impact.

If CPI is at or below target CPA:
- **Scaling path**: Raise budget first (safer than raising bid). Budget increase ≤ 20%/day.
- **If budget is not the constraint**: Raise bid in 10-15% increments, let stabilize for 7 days [gg-gem-1218].
- **Alternative to bid raises**: Add a new ad group to open new inventory [gg-gem-1293].

### Step 4: Evaluate tROAS Readiness (if user is considering switching)

tROAS requires ALL of these:
- [ ] Firebase integrated and sending events
- [ ] 10+ revenue events/day average over last 30 days
- [ ] Willing to accept higher CPI in exchange for better user quality [ab-pt-020]
- [ ] CPA campaign(s) will continue running alongside tROAS [ab-pt-012]

If all checked: tROAS is appropriate. Set initial target at 20% below actual ROAS [ab-pt-010], use 7-day conversion window, expect 2–3 week learning phase.

If any unchecked: Do not switch to tROAS. Flag which prerequisites are missing.

### Step 5: Check for Recent Destabilizing Changes

If bids or budgets changed > 20% in the last 14 days and performance is volatile:
- The campaign is likely in a disrupted learning phase
- **Do not make further changes** — let it stabilize for 7–14 more days
- Only intervene if spend collapses to near zero (then a small +10% bid nudge is warranted)

### Step 6: Output

\`\`\`
## Google Bid Strategy Assessment — [date]

### Campaign Snapshot

| Campaign | Strategy | Target | Actual | Daily Vol | Signal |
|----------|----------|--------|--------|-----------|--------|
| [name] | Target CPA | $2.50 | $3.10 | 45/day | ⚠️ Below threshold |
| [name] | Target ROAS | 200% | 180% | 12 events/day | ✅ Functional |

### Assessments

**[Campaign A] — Below algorithm threshold**
45 installs/day is below Google's 50/day minimum. The algorithm cannot optimize meaningfully at this volume. Increasing the budget to reach 80–100 installs/day will do more than any bid adjustment.
→ Do not reduce bids — it will worsen volume further.
→ Consolidate with [Campaign B] or increase daily budget by 20% increments.

**[Campaign B] — tROAS functioning but ROAS target too aggressive**
Actual ROAS is 180% vs 200% target. The campaign is underspending because the target is too high.
→ Lower target to 150% (20% below actual) to enter the learning zone, then raise gradually [ab-pt-010, gg-gem-1218].

### tROAS Readiness Check
[✅/❌ each prerequisite with notes]

### Scaling Path for [Campaign C]
Current: $X/day, [N] installs/day, CPI at target.
Recommended sequence:
1. Raise daily budget by 20% → wait 7 days → evaluate
2. If CPI holds: raise another 20% → wait 7 days
3. If CPI holds and budget is no longer the constraint: add a new ad group with a different creative angle [gg-gem-1293]
4. Only raise bids after budget increases stop generating volume gains
\`\`\`
`,
  "google-campaign-health": `# Skill: Google Campaign Health Check

Week-over-week performance comparison for Google App Campaigns — diagnoses spend, CPI, and install volume trends and flags campaigns that need action.

---

## When to Use This

- User asks "how are my Google campaigns doing?"
- User wants a Monday / start-of-week check on Google Ads
- Spend dropped or spiked unexpectedly on Google
- CPI is rising and the cause is unclear
- User wants to know if their Google campaigns are hitting algorithm thresholds

## What It Needs

**Option A — Google Ads connected**: \`GOOGLE_ADS_DEVELOPER_TOKEN\`, \`GOOGLE_ADS_CLIENT_ID\`, \`GOOGLE_ADS_CLIENT_SECRET\`, \`GOOGLE_ADS_REFRESH_TOKEN\` configured.

**Option B — CSV export**: No API needed. Export from Google Ads UI:
- Go to **Campaigns** → set date range to **This week (Mon–today)** and **Last week (Mon–Sun)**
- Columns to include: \`Campaign\`, \`Campaign type\`, \`Status\`, \`Budget\`, \`Impressions\`, \`Clicks\`, \`Installs\`, \`Cost\`, \`CPI\`, \`Conversions\`, \`Cost/conv.\`
- Export as CSV. Paste both exports (label which week each is).

## What It Produces

- Week-over-week delta table per campaign (spend Δ%, CPI Δ%, installs Δ%)
- Status per campaign: Healthy / Scaling / Degrading / Below threshold / Stalled
- Diagnosis for each flagged campaign
- Prioritized action list

---

## Knowledge Base Grounding

- **ab-pt-006** (Ashley Black): "Never change bids or budgets more than 20% per day — larger changes cause campaigns to tank and struggle to recover."
- **ab-pt-019** (Ashley Black): "Google recommends 50 installs/day or 10 actions/day — aim for double. Below threshold = algorithm can't optimize."
- **gg-gem-1293** (ex-Googler): "A way to scale without changing bids is to add a new ad group — new ad groups perform better than scaling bids on existing ones."
- **gg-gem-1294** (ex-Googler): "You can't go too small on Google UAC — $100/day is insufficient for the algorithm to work."
- **ab-pt-007** (Ashley Black): "Duplicate stale campaigns for a fresh start — the algorithm gets fatigued just like creative does."

---

## Procedure

### Step 1: Pull This Week and Last Week Data

**If API connected:**

\`\`\`
# This week
get_google_insights(
  customer_id="123-456-7890",
  date_range="THIS_WEEK_MON_TODAY",
  level="CAMPAIGN",
  metrics=["impressions","clicks","conversions","cost_micros","cost_per_conversion"]
)

# Last week
get_google_insights(
  customer_id="123-456-7890",
  date_range="LAST_WEEK",
  level="CAMPAIGN",
  metrics=["impressions","clicks","conversions","cost_micros","cost_per_conversion"]
)
\`\`\`

**If CSV:** Use the two exports the user pasted.

### Step 2: Compute Week-over-Week Deltas

For each campaign, calculate:
- Spend Δ%
- Installs / conversions Δ%
- CPI (cost per install) Δ%
- Daily install run rate this week vs last week

### Step 3: Apply Threshold Check

Flag any campaign where:
- Daily installs < 50 (or daily target events < 10) → **Below threshold** — algorithm can't optimize
- Daily budget < $100 → **Underfunded** — Google needs more signal
- CPI rose > 20% WoW with no bid change → **Degrading** — investigate creative or network shift
- Spend dropped > 30% WoW with no budget change → **Stalled** — check campaign status, bids, creative fatigue

### Step 4: Pull Campaign Structure (API only)

\`\`\`
get_google_ads_campaigns(customer_id="123-456-7890")
\`\`\`

Check for: campaigns that have been running > 90 days with no creative refresh (fatigue risk per ab-pt-007).

### Step 5: Diagnose and Recommend

For each flagged campaign, apply this logic:

| Signal | Diagnosis | Action |
|--------|-----------|--------|
| Below 50 installs/day | Insufficient signal | Increase budget OR consolidate campaigns |
| CPI up > 20%, impressions flat | Creative fatigue | Run \`google-asset-performance\` skill |
| CPI up > 20%, impressions down | Network shift | Run \`google-network-audit\` skill |
| Campaign running > 90 days, CPI rising | Algorithm fatigue | Duplicate campaign for a fresh start [ab-pt-007] |
| Spend dropped, status = active | Budget exhausted or low bid | Check budget cap; raise bid ≤ 20% [ab-pt-006] |

### Step 6: Output

Present:

\`\`\`
## Google Campaign Health — [date range]

| Campaign | Spend Δ | CPI Δ | Installs Δ | Status |
|----------|---------|-------|------------|--------|
| [name]   | +12%    | -8%   | +22%       | Healthy |
| [name]   | -5%     | +31%  | -28%       | Degrading |

### Flagged Campaigns

**[Campaign name] — Degrading**
CPI rose 31% WoW. Impressions are flat, suggesting creative fatigue rather than a network shift.
→ Run google-asset-performance to identify underperforming assets.
→ Do not increase bids — fix creative first.

### Threshold Check
- [Campaign] is below 50 installs/day (currently [N]/day). Algorithm cannot optimize at this volume.
  → Consider consolidating with another campaign or increasing budget.

### Recommended Actions (Priority Order)
1. ...
\`\`\`
`,
  "google-network-audit": `# Skill: Google Network Mix Audit

Analyze how Google App Campaign spend is distributed across its 5 networks — and whether that distribution is working for you or against you.

---

## When to Use This

- CPI suddenly spiked and the cause isn't obvious
- User suspects traffic quality has degraded
- After enabling a new campaign and wanting to understand where Google is sending spend
- User is comparing two campaigns with different CPI and wants to rule out network mix as the cause
- Before deciding whether to add placement exclusions

## What It Needs

**Option A — Google Ads connected:**

\`\`\`
get_google_network_mix(customer_id="123-456-7890", campaign_id="...")
get_google_insights(customer_id="123-456-7890", ..., breakdowns=["network"])
\`\`\`

**Option B — CSV export:** Export from Google Ads UI:
- Go to the **Campaigns** report → click **Segment** → **Network (with search partners)**
- Columns: \`Campaign\`, \`Network\`, \`Impressions\`, \`Clicks\`, \`Conversions\`, \`Cost\`, \`CPI\`, \`CTR\`
- Date range: last 14 days. Export as CSV and paste below.
- Note: Google's UI shows 4 buckets — Search, Display Network, YouTube, Cross-network. The full 5-network breakdown (including Play Store separately) requires a Google rep.

## What It Produces

- Network spend distribution table with CPI per network
- Identification of underperforming networks pulling the average up
- Flags for abnormal traffic shifts
- Placement exclusion recommendations where warranted

---

## Knowledge Base Grounding

- **ab-pt-005** (Ashley Black): "Google App Campaigns serve across 5 networks but the dashboard only shows 4 buckets. 'Search' includes both google.com AND Play Store search. 'Display Network' includes AdMob, MGDN (mobile browser), AND Play Store browse. 'YouTube' includes Shorts, in-stream, homepage, and bumper ads."
- **ab-pt-018** (Ashley Black): "Each traffic source has very different quality characteristics. Play Store search = high-intent (users actively searching). AdMob/MGDN = low-intent (interruption ads in other apps). Understanding the mix explains most unexplained CPI swings."
- **gg-gem-1177** (community): "Dig deep in the Google UI — the app placement report shows which specific apps/sites are serving your ads. Most advertisers never look at this. It's under Insights → Where ads showed."
- **gg-gem-1292** (ex-Googler): "You can see the 'Devices' breakdown under Insights → Where and When ads are shown → Devices. Sudden shifts between phone/tablet can explain CPI changes."
- **ab-pt-005** actionable: "Use Network segmentation to monitor traffic shifts. If you see a performance drop, check if traffic shifted to low-quality display/web placements."

---

## Procedure

### Step 1: Pull Network Distribution

**If API connected:**

\`\`\`
get_google_network_mix(
  customer_id="123-456-7890",
  campaign_id="[campaign_id]"
)

# Also pull with date comparison: this week vs last week
get_google_insights(
  customer_id="123-456-7890",
  campaign_id="[campaign_id]",
  date_range="LAST_14_DAYS",
  level="CAMPAIGN",
  metrics=["impressions","conversions","cost_micros","cost_per_conversion"],
  segment_by_network=true
)
\`\`\`

**If CSV:** Use the network-segmented export the user pasted.

### Step 2: Map Buckets to Real Traffic

Explain what each bucket actually contains to the user:

| UI Bucket | What's Actually Inside |
|-----------|------------------------|
| Search | google.com search results + Play Store search (high-intent) |
| Display Network | AdMob (in-app ads) + MGDN (mobile browser) + Play Store browse |
| YouTube | In-stream, YouTube Shorts, homepage, bumper ads |
| Cross-network | Mixed; often a small residual bucket |

### Step 3: Calculate CPI by Network

For each bucket:
- Spend share (% of total)
- CPI relative to campaign average
- Install share (% of total installs)

Flag any bucket where:
- Spend share > 30% AND CPI > 1.5× campaign average → **High-cost network drag**
- Spend share increased > 10pp WoW → **Traffic shift** — likely cause of any CPI change

### Step 4: Check Placement Report (API or Manual)

**If API connected:** Look for specific underperforming app/site placements within Display Network.

**If manual:** Advise user to check: Google Ads UI → **Insights** → **Where ads showed** → filter by Display Network → sort by Cost desc → look for non-app placements (web URLs) with high cost and zero installs.

Placement exclusion is warranted when:
- A specific app/site accounts for > 5% of Display spend with CPI > 3× target
- Web (non-app) placements are appearing in an app install campaign

### Step 5: Check Device Split

Advise user to check: Google Ads UI → **Insights** → **Devices**. A sudden shift from phone to tablet traffic frequently explains CPI increases — tablets convert at a much lower rate for most apps.

### Step 6: Output

\`\`\`
## Google Network Mix Audit — [campaign] — [date range]

### Network Distribution

| Network | Spend Share | CPI | vs Avg | Trend |
|---------|-------------|-----|--------|-------|
| Search (google.com + Play search) | 42% | $1.80 | -28% | Stable |
| Display (AdMob + MGDN + Play browse) | 38% | $3.90 | +56% | ↑ +8pp WoW |
| YouTube | 20% | $2.20 | -12% | Stable |

### Diagnosis

Display Network is pulling the overall CPI up significantly. Its spend share grew 8pp last week — this shift likely explains the overall CPI increase.

Within Display, check your placement report for non-app (web) URLs — these tend to be low-quality for app install campaigns.

### Recommended Actions
1. Run the placement report (Insights → Where ads showed → Display) and exclude any web URLs with >$X spend and zero installs.
2. Do not exclude the entire Display Network — Play Store browse is high-intent inventory within that bucket.
3. Monitor the network split weekly — a 5pp+ shift is worth investigating.

### What You Can't Control
Google's algorithm automatically shifts spend across networks based on auction signals. You can exclude specific placements but cannot directly cap network-level spend. The levers are: bid adjustments, placement exclusions, and creative quality (better creatives attract better placements).
\`\`\`
`,
  "placement-audit": `# Skill: Placement Efficiency Audit

How to identify and quantify placement waste in Meta app install campaigns.

---

## When to Use This

- Campaign has high CPI and you suspect placement waste
- Comparing an efficient vs inefficient campaign
- After enabling Advantage+ placements and wanting to check what Meta chose
- Before deciding whether to restrict placements or keep them broad
- User asks "where is Meta spending my money?" or "should I turn off certain placements?"

## What It Needs

**Option A — Meta API connected**: Provide \`ad_account_id\`.

**Option B — CSV export** (no API needed):
- Go to **Meta Ads Manager** → **Campaigns** or **Ads** tab
- Date range: **Last 7 days**
- Click **Breakdown** → **By Delivery** → **Platform** (then repeat with **Placement**)
- Columns: \`Platform\`, \`Placement\`, \`Spend\`, \`Impressions\`, \`CPM\`, \`CTR (link)\`, \`Result\`, \`Cost per result\`
- Export as CSV and paste below.

## What It Produces

- Spend and CPA breakdown by placement (Reels, Feed, Stories, Audience Network, etc.)
- Waste quantification: how much is going to high-CPA placements
- Placement restriction recommendations with expected CPA impact
- Value Rules recommendation for placement-level bid modifiers

---

## Knowledge Base Grounding

- **mb-li-006** (Marcus Burke): "App Promotion campaigns are Reels-heavy and skew young. Web campaigns have better placement distribution and scale on Feed."
- **mb-li-009** (Marcus Burke): "Placement-level Value Rules — bid differently on each placement within the same broad targeting ad set. Don't create separate placement-targeted campaigns."

---

## Step 1: Pull Placement Breakdown

\`\`\`
get_meta_insights(
  ad_account_id="act_123456789",
  level="campaign",
  fields="spend,impressions,cpm,ctr,actions,cost_per_action_type",
  breakdowns="publisher_platform,platform_position",
  date_preset="last_7d"
)
\`\`\`

Returns one row per \`publisher_platform\` × \`platform_position\` combination.

---

## Step 2: Calculate CPI Per Placement

For each placement row:
\`\`\`
installs = actions where action_type == "mobile_app_install"
cpi = spend / installs (if installs > 0, else ∞)
\`\`\`

Build a table sorted by spend descending:

| Placement | Spend | Impressions | Installs | CPI | % of Total Spend |
|---|---|---|---|---|---|

---

## Step 3: Flag Waste Placements

**Rule of thumb**: Flag any placement where CPI > 3x the campaign average CPI.

### Common Waste Placements for iOS App Install Campaigns

| Placement | Typical Behavior | Why It's Wasteful |
|---|---|---|
| \`facebook/instream_video\` | Very high impressions, very low installs | Users watching videos don't want to leave; accidental clicks |
| \`facebook/facebook_reels_overlay\` | High impressions, very low installs | Overlay ads get impressions but no meaningful engagement |
| \`threads/threads_feed\` | Low volume, near-zero installs | Threads audience isn't app-install-receptive (yet) |
| \`audience_network/classic\` | Can drive volume but often low quality | Third-party apps, less intent |

**Campaign type context** [mb-li-006]: App Promotion campaigns are inherently Reels-heavy. If you need better placement distribution, consider Web Sales campaigns which scale more on Feed.

### Example from ROLA vs MX Analysis

**Efficient campaign (ROLA)** — only 6 placements, CPI range $3.06 - $6.86:
- instagram/reels: $3.37
- facebook/reels: $3.64
- instagram/stories: $3.64
- facebook/stories: $3.94
- instagram/feed: $3.06
- facebook/feed: $6.86

**Inefficient campaign (MX)** — 8 placements, CPI range $8.64 - $83.66:
- facebook/instream_video: **$83.66** (29 installs for $2,426)
- facebook/reels_overlay: **$56.98** (31 installs for $1,766)
- threads/threads_feed: **∞** (0 installs for $53)
- instagram/stories: $31.07
- facebook/feed: $20.93
- facebook/stories: $14.02
- instagram/reels: $10.12
- facebook/reels: $8.64

The 3 waste placements in MX burned **$4,245 for 60 installs ($70.75 CPI)** — but even without them, MX's core placements are 2-4x more expensive than ROLA's.

---

## Step 4: Quantify the Waste

Calculate:
- **Total waste spend**: Sum of spend on placements with CPI > 3x average
- **Waste installs**: Sum of installs from those placements
- **Waste CPI**: waste spend / waste installs
- **What-if CPI**: (total spend - waste spend) / (total installs - waste installs)

### Example
\`\`\`
MX total: $36,934 spend, 2,434 installs, $15.17 CPI

Waste placements: $4,245 spend, 60 installs
Without waste: $32,689 spend, 2,374 installs = $13.77 CPI

Savings: $1.40 CPI improvement (9.2% better)
But still 3.5x worse than ROLA — waste is a symptom, not the full cause
\`\`\`

---

## Step 5: Compare Placement Mix Between Campaigns

| Placement | Campaign A (% spend) | Campaign B (% spend) |
|---|---|---|
| instagram/reels | | |
| facebook/reels | | |
| facebook/feed | | |
| instagram/stories | | |
| facebook/stories | | |
| instagram/feed | | |
| [waste placements] | | |

**Watch for**:
- Campaign A has 80% spend on reels/stories (video-first, high-intent placements)
- Campaign B has 40% on feed + 12% on junk placements (broader, lower-intent)

---

## Step 6: Decision — Restrict vs Advantage+ vs Value Rules

### Option 1: Restrict Placements
**When**: Clear waste placements with CPI > 5x average, waste >10% of total budget, >30 days of data.

**Warning**: Restricting placements resets the learning phase. Monitor closely for 3-5 days.

### Option 2: Keep Advantage+ Broad
**When**: All placements within 2x of average CPI, campaign is new (<14 days), Advantage+ is still learning.

### Option 3: Placement Value Rules [mb-li-009]
**When**: You want to keep broad targeting but bid differently per placement. "This avoids fragmentation from creating separate placement-targeted campaigns."

Set up Placement-level Value Rules to bid lower on wasteful placements and higher on efficient ones, within the same ad set. This is the preferred approach when:
- You want to maintain broad delivery
- Waste is moderate (not extreme)
- You have enough data to know which placements work

---

## Step 7: Monitor After Changes

\`\`\`
get_meta_insights(
  ad_account_id="act_123456789",
  level="campaign",
  fields="spend,impressions,actions",
  time_increment="1",
  date_preset="last_14d"
)
\`\`\`

Check:
- Did CPI improve within 3-5 days?
- Did impression volume drop significantly?
- Did install volume stay stable or improve?
- Did CPM increase? (expected — higher-quality placements cost more)

---

## Output Template

\`\`\`markdown
## Placement Audit: [Campaign Name]

### Placement Performance
| Placement | Spend | Installs | CPI | Flag |
|---|---|---|---|---|
| | | | | OK / WASTE |

### Waste Summary
- Total waste: $X on Y placements
- Waste CPI: $Z (vs campaign average $W)
- Impact if removed: CPI improves from $A to $B

### Recommendation
[Restrict placements / Keep broad / Use Placement Value Rules [mb-li-009]]

### Knowledge Base References
- mb-li-006, mb-li-009
\`\`\`
`,
  "weekly-performance": `# Skill: Weekly Performance Snapshot

The "Monday morning check" — week-over-week health comparison with automatic diagnosis using Kast's diagnostic framework.

---

## When to Use This

- User asks "how did we do this week?" or "how are campaigns performing?"
- Monday morning or start-of-week check-in
- Spend, CPA, or ROAS changed unexpectedly and needs diagnosis
- User wants a summary before an optimization session
- User says "quick check" or "weekly recap"

## What It Needs

**Option A — Meta API connected**: Provide \`ad_account_id\` (e.g. \`act_123456789\`).

**Option B — CSV export** (no API needed):
- Go to **Meta Ads Manager** → **Campaigns** tab
- Set date range to **This week (Mon–today)**, then export. Repeat for **Last week (Mon–Sun)**.
- Columns to include: \`Campaign name\`, \`Delivery\`, \`Budget\`, \`Spend\`, \`Reach\`, \`Impressions\`, \`Frequency\`, \`CPM\`, \`CTR (link)\`, \`CPC\`, \`Result\` (your conversion event), \`Cost per result\`
- Export each week as a separate CSV and paste both below, labeled by week.

## What It Produces

- Week-over-week delta table per campaign (spend Δ%, CPA Δ%, CPM Δ%, CTR Δ%, frequency Δ%)
- Kast diagnostic label per campaign (fatigue / saturation / LP mismatch / healthy)
- Prioritized action list

---

## Knowledge Base Grounding

- **wk-tw-001** (William Kast): The 4 core metric patterns that diagnose every Meta performance issue:
  1. Frequency↑ + CPA↑ → creative fatigue → need fresh TOF creatives
  2. CPM↑ + CPA↑ → audience saturation or poor engagement → new messaging, new audiences
  3. CPA↑ + CVR↓ → ad-to-landing-page mismatch → fix landing page alignment
  4. CTR↓ + CPA↑ → creative fatigue → need fresh TOF creatives
- **wk-tw-002** (William Kast): ROAS troubleshooting decision tree — CPM → CTR → AOV → CR, sequential isolation
- **ds-pt-001** (Dara Saeed): "Primary metrics (spend, CPA, ROAS) decide what works. Secondary metrics (frequency, CPM, CTR) explain why. Never make optimization decisions based on secondary metrics alone."
- **ds-pt-008** (Dara Saeed): "Analyze first, optimize second. Separate the two activities to avoid reactive decisions."

---

## Procedure

### Step 1: Pull This Week and Last Week Data

\`\`\`
# This week
get_meta_insights(
  ad_account_id="act_123456789",
  level="campaign",
  fields="campaign_id,campaign_name,spend,impressions,clicks,ctr,cpm,cpc,reach,frequency,actions,cost_per_action_type",
  date_preset="this_week_mon_today"
)

# Last week
get_meta_insights(
  ad_account_id="act_123456789",
  level="campaign",
  fields="campaign_id,campaign_name,spend,impressions,clicks,ctr,cpm,cpc,reach,frequency,actions,cost_per_action_type",
  date_preset="last_week_mon_sun"
)
\`\`\`

### Step 2: Compute Deltas

For each campaign, calculate week-over-week changes:
- Spend Δ%
- CPA Δ%
- CPM Δ%
- CTR Δ%
- Frequency Δ%
- Conversions Δ%

### Step 3: Apply Kast Diagnostic Framework [wk-tw-001]

For each campaign with CPA increase, check which pattern matches:

| Pattern | Diagnosis | Action |
|---------|-----------|--------|
| Frequency↑ + CPA↑ | Creative fatigue | Fresh TOF creatives needed |
| CPM↑ + CPA↑ | Audience saturation / poor engagement | New messaging, broader targeting |
| CPA↑ + CVR↓ | Ad-to-LP mismatch | Fix landing page alignment |
| CTR↓ + CPA↑ | Creative fatigue | New hooks, new creative concepts |

Remember: "Primary metrics decide what works. Secondary metrics explain why" [ds-pt-001].

### Step 4: Generate Action Items

Prioritize the top 3 highest-impact actions across all campaigns.

---

## Output Template

\`\`\`markdown
## Weekly Performance Snapshot — [Date Range]

### Account Summary
Total spend: $X (+Y% WoW) | Conversions: N (+Z% WoW) | Avg CPA: $X (+W% WoW)

### Campaign Health
| Campaign | Spend | CPA (Δ%) | CPM (Δ%) | CTR (Δ%) | Freq | Diagnosis |
|----------|-------|----------|----------|----------|------|-----------|
| Camp A   | $5K   | $12 (+8%)| $15 (+12%)| 1.2% (-5%)| 2.1 | ⚠ CPM+CPA↑: audience saturation [wk-tw-001 #2] |
| Camp B   | $3K   | $9 (-3%) | $11 (0%) | 1.8% (+2%)| 1.5 | ✅ Healthy |

### Diagnosis
[Per Kast framework, with insight IDs]

### Action Items
1. [Highest impact action]
2. [...]
3. [...]

> "Analyze first, optimize second" (ds-pt-008) — review this report fully before making changes.

### Knowledge Base References
- wk-tw-001, wk-tw-002, ds-pt-001, ds-pt-008
\`\`\`
`,
};
