#!/usr/bin/env tsx
// Reads skills/*.md and generates supabase/functions/_shared/prompt-content.ts
// Run with: npm run build:prompts

import { readFileSync, writeFileSync, readdirSync } from "fs";
import { join, basename, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const SKILLS_DIR = join(__dirname, "..", "skills");
const OUTPUT = join(
  __dirname,
  "..",
  "supabase",
  "functions",
  "_shared",
  "prompt-content.ts"
);

// Map from .md filename (without extension) to prompt name.
// Only files that correspond to MCP prompts are included.
const FILE_TO_PROMPT: Record<string, string> = {
  "ad-fatigue-report": "ad-fatigue-report",
  "weekly-performance": "weekly-performance",
  "creative-performance": "creative-performance",
  "audience-composition": "audience-composition",
  "campaign-architecture-review": "architecture-review",
  "audit-meta-account": "audit-meta-account",
  "campaign-comparison": "campaign-comparison",
  "placement-audit": "placement-audit",
  "attribution-analysis": "attribution-analysis",
};

const entries: string[] = [];

for (const file of readdirSync(SKILLS_DIR).sort()) {
  if (!file.endsWith(".md")) continue;
  const stem = basename(file, ".md");
  const promptName = FILE_TO_PROMPT[stem];
  if (!promptName) continue; // skip admin-internal files (extract-insights, ingest-content)

  const content = readFileSync(join(SKILLS_DIR, file), "utf-8");
  // Escape backticks and ${} for template literal safety
  const escaped = content.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
  entries.push(`  "${promptName}": \`${escaped}\``);
}

const output = `// Auto-generated by scripts/build-prompt-content.ts — DO NOT EDIT
// Run: npm run build:prompts

export const promptContent: Record<string, string> = {
${entries.join(",\n")},
};
`;

writeFileSync(OUTPUT, output, "utf-8");
console.log(`Generated ${OUTPUT} with ${entries.length} prompts`);
